/** Generates the fully unrolled BLAKE3 compression in src/blake3.ts. */
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const START = '// BEGIN generated BLAKE3 compression';
const END = '// END generated BLAKE3 compression';

// BLAKE3's message permutation is applied between each of seven rounds.
const MSG_PERMUTATION = [2, 6, 3, 10, 7, 0, 4, 13, 1, 11, 12, 5, 9, 14, 15, 8];
const OFFICIAL_SCHEDULES = [
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
  [2, 6, 3, 10, 7, 0, 4, 13, 1, 11, 12, 5, 9, 14, 15, 8],
  [3, 4, 10, 12, 13, 2, 7, 14, 6, 5, 9, 0, 11, 15, 8, 1],
  [10, 7, 12, 9, 14, 3, 13, 15, 4, 0, 11, 2, 5, 8, 1, 6],
  [12, 13, 9, 11, 15, 10, 14, 8, 7, 2, 5, 3, 0, 1, 6, 4],
  [9, 14, 11, 5, 8, 12, 15, 1, 13, 3, 0, 10, 2, 6, 4, 7],
  [11, 15, 5, 0, 1, 9, 8, 6, 14, 10, 2, 12, 3, 4, 7, 13],
];

function schedules() {
  const out = [];
  for (let round = 0, schedule = OFFICIAL_SCHEDULES[0]; round < 7; round++) {
    out.push(schedule);
    schedule = MSG_PERMUTATION.map((i) => schedule[i]);
  }
  assert.deepEqual(out, OFFICIAL_SCHEDULES);
  return out;
}

// Four column Gs followed by four diagonal Gs. Each G is emitted in full before the next one.
const G_INDICES = [
  [0, 4, 8, 12],
  [1, 5, 9, 13],
  [2, 6, 10, 14],
  [3, 7, 11, 15],
  [0, 5, 10, 15],
  [1, 6, 11, 12],
  [2, 7, 8, 13],
  [3, 4, 9, 14],
];

function genG([a, b, c, d], mx, my) {
  return `  v${a} = (v${a} + v${b} + m${mx}) | 0; v${d} ^= v${a}; v${d} = (v${d} >>> 16) | (v${d} << 16);
  v${c} = (v${c} + v${d}) | 0; v${b} ^= v${c}; v${b} = (v${b} >>> 12) | (v${b} << 20);
  v${a} = (v${a} + v${b} + m${my}) | 0; v${d} ^= v${a}; v${d} = (v${d} >>> 8) | (v${d} << 24);
  v${c} = (v${c} + v${d}) | 0; v${b} ^= v${c}; v${b} = (v${b} >>> 7) | (v${b} << 25);`;
}

function genRound(schedule, round) {
  const out = [`  // Round ${round}: ${schedule.join(', ')}`, '  // columns'];
  for (let i = 0; i < 4; i++) out.push(genG(G_INDICES[i], schedule[2 * i], schedule[2 * i + 1]));
  out.push('  // diagonals');
  for (let i = 4; i < 8; i++) out.push(genG(G_INDICES[i], schedule[2 * i], schedule[2 * i + 1]));
  return out.join('\n');
}

function generate() {
  const messages = Array.from(
    { length: 16 },
    (_, i) => `m${i} = msg[offset${i ? ` + ${i}` : ''}] | 0`
  );
  const messageLoads = [];
  for (let i = 0; i < messages.length; i += 4) {
    messageLoads.push(`  const ${messages.slice(i, i + 4).join(', ')};`);
  }
  return `${START}
// Generated by test/misc/unrolled-blake3.js. Do not edit by hand.
// prettier-ignore
function b3Compress(
  msg: TArg<Uint32Array>,
  offset: number,
  cv: TArg<Uint32Array>,
  t0: number,
  t1: number,
  blockLen: number,
  flags: number,
  out?: TArg<Uint32Array>
) {
  const c0 = cv[0] | 0, c1 = cv[1] | 0, c2 = cv[2] | 0, c3 = cv[3] | 0;
  const c4 = cv[4] | 0, c5 = cv[5] | 0, c6 = cv[6] | 0, c7 = cv[7] | 0;
${messageLoads.join('\n')}
  let v0 = c0, v1 = c1, v2 = c2, v3 = c3, v4 = c4, v5 = c5, v6 = c6, v7 = c7;
  let v8 = 0x6a09e667 | 0, v9 = 0xbb67ae85 | 0, v10 = 0x3c6ef372 | 0, v11 = 0xa54ff53a | 0;
  let v12 = t0 | 0, v13 = t1 | 0, v14 = blockLen | 0, v15 = flags | 0;
${schedules().map(genRound).join('\n')}
  const dst = out || cv;
  dst[0] = v0 ^ v8; dst[1] = v1 ^ v9; dst[2] = v2 ^ v10; dst[3] = v3 ^ v11;
  dst[4] = v4 ^ v12; dst[5] = v5 ^ v13; dst[6] = v6 ^ v14; dst[7] = v7 ^ v15;
  if (out) {
    out[8] = v8 ^ c0; out[9] = v9 ^ c1; out[10] = v10 ^ c2; out[11] = v11 ^ c3;
    out[12] = v12 ^ c4; out[13] = v13 ^ c5; out[14] = v14 ^ c6; out[15] = v15 ^ c7;
  }
}
${END}`;
}

const generated = generate();
if (process.argv[2] === '--check') {
  const source = readFileSync(new URL('../../src/blake3.ts', import.meta.url), 'utf8');
  const start = source.indexOf(START);
  const end = source.indexOf(END, start);
  assert.notEqual(start, -1, `missing source marker: ${START}`);
  assert.notEqual(end, -1, `missing source marker: ${END}`);
  assert.equal(source.slice(start, end + END.length), generated);
  console.log('src/blake3.ts compression matches generator');
} else if (process.argv.length === 2) {
  console.log(generated);
} else {
  console.error('Usage: node test/misc/unrolled-blake3.js [--check]');
  process.exitCode = 1;
}
