/** Generates the fixed BLAKE2b schedule and fully unrolled BLAKE2s compression. */
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';

const B_START = '// BEGIN generated BLAKE2b compression';
const B_END = '// END generated BLAKE2b compression';
const S_START = '// BEGIN generated BLAKE2s compression';
const S_END = '// END generated BLAKE2s compression';

// RFC 7693, section 2.7: the ten distinct SIGMA rows. BLAKE2b rounds 10 and 11 repeat 0 and 1.
const OFFICIAL_SIGMA = [
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
  [14, 10, 4, 8, 9, 15, 13, 6, 1, 12, 0, 2, 11, 7, 5, 3],
  [11, 8, 12, 0, 5, 2, 15, 13, 10, 14, 3, 6, 7, 1, 9, 4],
  [7, 9, 3, 1, 13, 12, 11, 14, 2, 6, 5, 10, 4, 0, 15, 8],
  [9, 0, 5, 7, 2, 4, 10, 15, 14, 1, 11, 12, 6, 8, 3, 13],
  [2, 12, 6, 10, 0, 11, 8, 3, 4, 13, 7, 5, 15, 14, 1, 9],
  [12, 5, 1, 15, 14, 13, 4, 10, 0, 7, 6, 3, 9, 2, 8, 11],
  [13, 11, 7, 14, 12, 1, 3, 9, 5, 0, 15, 4, 8, 6, 2, 10],
  [6, 15, 14, 9, 11, 3, 0, 8, 12, 2, 13, 7, 1, 4, 10, 5],
  [10, 2, 8, 4, 7, 6, 1, 5, 15, 11, 9, 14, 3, 12, 13, 0],
];
const EXPECTED_FLAT = [
  0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 14, 10, 4, 8, 9, 15, 13, 6, 1, 12, 0, 2, 11,
  7, 5, 3, 11, 8, 12, 0, 5, 2, 15, 13, 10, 14, 3, 6, 7, 1, 9, 4, 7, 9, 3, 1, 13, 12, 11, 14, 2, 6,
  5, 10, 4, 0, 15, 8, 9, 0, 5, 7, 2, 4, 10, 15, 14, 1, 11, 12, 6, 8, 3, 13, 2, 12, 6, 10, 0, 11, 8,
  3, 4, 13, 7, 5, 15, 14, 1, 9, 12, 5, 1, 15, 14, 13, 4, 10, 0, 7, 6, 3, 9, 2, 8, 11, 13, 11, 7, 14,
  12, 1, 3, 9, 5, 0, 15, 4, 8, 6, 2, 10, 6, 15, 14, 9, 11, 3, 0, 8, 12, 2, 13, 7, 1, 4, 10, 5, 10,
  2, 8, 4, 7, 6, 1, 5, 15, 11, 9, 14, 3, 12, 13, 0,
];

function schedules() {
  const flat = OFFICIAL_SIGMA.flat();
  assert.deepEqual(flat, EXPECTED_FLAT);
  for (const row of OFFICIAL_SIGMA)
    assert.deepEqual(
      [...row].sort((a, b) => a - b),
      OFFICIAL_SIGMA[0]
    );
  return OFFICIAL_SIGMA;
}

const G = [
  [0, 4, 8, 12],
  [1, 5, 9, 13],
  [2, 6, 10, 14],
  [3, 7, 11, 15],
  [0, 5, 10, 15],
  [1, 6, 11, 12],
  [2, 7, 8, 13],
  [3, 4, 9, 14],
];

export function generateB() {
  const rounds = [...schedules(), schedules()[0], schedules()[1]];
  const calls = rounds.flatMap((sigma, round) => [
    `    // Round ${round}`,
    ...G.map(
      ([a, b, c, d], i) =>
        `    Gb(${a}, ${b}, ${c}, ${d}, msg, offset + ${2 * sigma[2 * i]}, offset + ${2 * sigma[2 * i + 1]});`
    ),
  ]);
  return `${B_START}
    // Generated by test/misc/unrolled-blake2.js from RFC 7693 SIGMA. Do not edit by hand.
${calls.join('\n')}
    ${B_END}`;
}

function half([a, b, c, d], x, second) {
  const rd = second ? 8 : 16;
  const rb = second ? 7 : 12;
  return [
    `    v${a} = (v${a} + v${b} + m${x}) | 0;`,
    `    v${d} = ((v${d} ^ v${a}) >>> ${rd}) | ((v${d} ^ v${a}) << ${32 - rd});`,
    `    v${c} = (v${c} + v${d}) | 0;`,
    `    v${b} = ((v${b} ^ v${c}) >>> ${rb}) | ((v${b} ^ v${c}) << ${32 - rb});`,
  ];
}

// Stage four independent G chains at each step. This exposes instruction-level parallelism without
// changing the RFC data dependencies and is the best tested portable BLAKE2s shape.
function sRound(sigma, round) {
  const out = [`    // Round ${round}`];
  for (let group = 0; group < 2; group++) {
    const gs = G.slice(group * 4, group * 4 + 4);
    for (let second = 0; second < 2; second++) {
      const base = group * 8;
      for (let step = 0; step < 4; step++) {
        for (let lane = 0; lane < 4; lane++) {
          const line = half(gs[lane], sigma[base + 2 * lane + second], second)[step];
          out.push(line);
        }
      }
    }
  }
  return out.join('\n');
}

export function generateS() {
  const loads = Array.from({ length: 16 }, (_, i) => `m${i} = msg[offset + ${i}] | 0`);
  const loadLines = [];
  for (let i = 0; i < loads.length; i += 4)
    loadLines.push(`    const ${loads.slice(i, i + 4).join(', ')};`);
  return `${S_START}
  // Generated by test/misc/unrolled-blake2.js from RFC 7693 SIGMA. Do not edit by hand.
  // prettier-ignore
  protected compress(msg: Uint32Array, offset: number, isLast: boolean): void {
    const length = this.length;
    let v0 = this.v0 | 0, v1 = this.v1 | 0, v2 = this.v2 | 0, v3 = this.v3 | 0;
    let v4 = this.v4 | 0, v5 = this.v5 | 0, v6 = this.v6 | 0, v7 = this.v7 | 0;
    // B2S_IV is a module-evaluation snapshot of exported mutable SHA256_IV; retain those semantics.
    let v8 = B2S_IV[0] | 0, v9 = B2S_IV[1] | 0, v10 = B2S_IV[2] | 0, v11 = B2S_IV[3] | 0;
    let v12 = (B2S_IV[4] ^ (length >>> 0)) | 0, v13 = (B2S_IV[5] ^ ((length / 4294967296) | 0)) | 0;
    let v14 = (isLast ? ~B2S_IV[6] : B2S_IV[6]) | 0, v15 = B2S_IV[7] | 0;
${loadLines.join('\n')}
${schedules().map(sRound).join('\n')}
    this.v0 = (this.v0 ^ v0 ^ v8) | 0; this.v1 = (this.v1 ^ v1 ^ v9) | 0;
    this.v2 = (this.v2 ^ v2 ^ v10) | 0; this.v3 = (this.v3 ^ v3 ^ v11) | 0;
    this.v4 = (this.v4 ^ v4 ^ v12) | 0; this.v5 = (this.v5 ^ v5 ^ v13) | 0;
    this.v6 = (this.v6 ^ v6 ^ v14) | 0; this.v7 = (this.v7 ^ v7 ^ v15) | 0;
  }
  ${S_END}`;
}

function checkRegion(source, startMarker, endMarker, generated) {
  const start = source.indexOf(startMarker);
  const end = source.indexOf(endMarker, start);
  assert.notEqual(start, -1, `missing source marker: ${startMarker}`);
  assert.notEqual(end, -1, `missing source marker: ${endMarker}`);
  assert.equal(source.slice(start, end + endMarker.length), generated);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const generatedB = generateB();
  const generatedS = generateS();
  if (process.argv[2] === '--check') {
    const source = readFileSync(new URL('../../src/blake2.ts', import.meta.url), 'utf8');
    checkRegion(source, B_START, B_END, generatedB);
    checkRegion(source, S_START, S_END, generatedS);
    console.log('src/blake2.ts compressions match generator');
  } else if (process.argv.length === 2) {
    console.log(generatedB + '\n\n' + generatedS);
  } else {
    console.error('Usage: node test/misc/unrolled-blake2.js [--check]');
    process.exitCode = 1;
  }
}
