/** Generates the statically scheduled Keccak-p[1600] round in src/sha3.ts. */
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const START = '// BEGIN generated SHA3 permutation';
const END = '// END generated SHA3 permutation';

// FIPS 202 round constants, written as ordinary 64-bit hex for independent verification.
const OFFICIAL_IOTA = [
  '0000000000000001',
  '0000000000008082',
  '800000000000808a',
  '8000000080008000',
  '000000000000808b',
  '0000000080000001',
  '8000000080008081',
  '8000000000008009',
  '000000000000008a',
  '0000000000000088',
  '0000000080008009',
  '000000008000000a',
  '000000008000808b',
  '800000000000008b',
  '8000000000008089',
  '8000000000008003',
  '8000000000008002',
  '8000000000000080',
  '000000000000800a',
  '800000008000000a',
  '8000000080008081',
  '8000000000008080',
  '0000000080000001',
  '8000000080008008',
].map((n) => BigInt(`0x${n}`));

// FIPS 202 Algorithm 5 rc(): generate Iota constants from the 8-bit LFSR.
function iotas() {
  const out = [];
  let R = 1n;
  for (let round = 0; round < 24; round++) {
    let value = 0n;
    for (let j = 0; j < 7; j++) {
      R = ((R << 1n) ^ ((R >> 7n) * 0x71n)) % 256n;
      if (R & 2n) value ^= 1n << ((1n << BigInt(j)) - 1n);
    }
    out.push(value);
  }
  assert.deepEqual(out, OFFICIAL_IOTA);
  return out;
}

// FIPS 202 section 3.2.2: the 24 non-(0,0) lanes form one Pi cycle, while the
// triangular numbers give the matching Rho offsets.
function schedules() {
  const pi = [];
  const rot = [];
  for (let round = 0, x = 1, y = 0; round < 24; round++) {
    [x, y] = [y, (2 * x + 3 * y) % 5];
    pi.push(2 * (5 * y + x));
    rot.push((((round + 1) * (round + 2)) / 2) % 64);
  }
  assert.deepEqual(
    pi,
    [20, 14, 22, 34, 36, 6, 10, 32, 16, 42, 48, 8, 30, 46, 38, 26, 24, 4, 40, 28, 44, 18, 12, 2]
  );
  assert.deepEqual(
    rot,
    [1, 3, 6, 10, 15, 21, 28, 36, 45, 55, 2, 14, 27, 41, 56, 8, 25, 43, 62, 18, 39, 61, 20, 44]
  );
  return { pi, rot };
}

const hex32 = (n) => `0x${n.toString(16).padStart(8, '0')}`;
const rotH = (h, l, s) =>
  s > 32
    ? `((${l} << ${s - 32}) | (${h} >>> ${64 - s}))`
    : `((${h} << ${s}) | (${l} >>> ${32 - s}))`;
const rotL = (h, l, s) =>
  s > 32
    ? `((${h} << ${s - 32}) | (${l} >>> ${64 - s}))`
    : `((${l} << ${s}) | (${h} >>> ${32 - s}))`;

function generate() {
  const constants = iotas();
  const iotaLo = constants.map((n) => Number(n & 0xffffffffn));
  const iotaHi = constants.map((n) => Number((n >> 32n) & 0xffffffffn));
  const { pi, rot } = schedules();
  const out = [
    START,
    '// Generated by test/misc/unrolled-sha3.js. Do not edit by hand.',
    '// prettier-ignore',
    `const SHA3_IOTA_LO = /* @__PURE__ */ Uint32Array.from([${iotaLo.map(hex32).join(', ')}]);`,
    '// prettier-ignore',
    `const SHA3_IOTA_HI = /* @__PURE__ */ Uint32Array.from([${iotaHi.map(hex32).join(', ')}]);`,
    '',
    '// prettier-ignore',
    'function keccakP1600(s: TArg<Uint32Array>, rounds: number): void {',
    '  let h: number, l: number, sh: number, sl: number;',
    '  let b0: number, b1: number, b2: number, b3: number, b4: number;',
    '  let b5: number, b6: number, b7: number, b8: number, b9: number;',
    '  for (let round = 24 - rounds; round < 24; round++) {',
    '    // Theta θ',
  ];
  for (let x = 0; x < 10; x++)
    out.push(`    b${x} = s[${x}] ^ s[${x + 10}] ^ s[${x + 20}] ^ s[${x + 30}] ^ s[${x + 40}];`);
  for (let x = 0; x < 10; x += 2) {
    const next = (x + 2) % 10;
    const prev = (x + 8) % 10;
    out.push(`    h = ((b${next} << 1) | (b${next + 1} >>> 31)) ^ b${prev};`);
    out.push(`    l = ((b${next + 1} << 1) | (b${next} >>> 31)) ^ b${prev + 1};`);
    for (let y = 0; y < 50; y += 10) out.push(`    s[${x + y}] ^= h; s[${x + y + 1}] ^= l;`);
  }
  out.push('    // Rho ρ and Pi π', '    sh = s[2]; sl = s[3];');
  for (let t = 0; t < 24; t++) {
    const p = pi[t];
    out.push(`    h = ${rotH('sh', 'sl', rot[t])}; l = ${rotL('sh', 'sl', rot[t])};`);
    out.push(`    sh = s[${p}]; sl = s[${p + 1}]; s[${p}] = h; s[${p + 1}] = l;`);
  }
  out.push('    // Chi χ');
  for (let y = 0; y < 50; y += 10) {
    out.push(`    b0 = s[${y}]; b1 = s[${y + 1}]; b2 = s[${y + 2}]; b3 = s[${y + 3}];`);
    out.push(
      `    s[${y}] ^= ~s[${y + 2}] & s[${y + 4}]; s[${y + 1}] ^= ~s[${y + 3}] & s[${y + 5}];`
    );
    out.push(
      `    s[${y + 2}] ^= ~s[${y + 4}] & s[${y + 6}]; s[${y + 3}] ^= ~s[${y + 5}] & s[${y + 7}];`
    );
    out.push(
      `    s[${y + 4}] ^= ~s[${y + 6}] & s[${y + 8}]; s[${y + 5}] ^= ~s[${y + 7}] & s[${y + 9}];`
    );
    out.push(`    s[${y + 6}] ^= ~s[${y + 8}] & b0; s[${y + 7}] ^= ~s[${y + 9}] & b1;`);
    out.push(`    s[${y + 8}] ^= ~b0 & b2; s[${y + 9}] ^= ~b1 & b3;`);
  }
  out.push(
    '    // Iota ι',
    '    s[0] ^= SHA3_IOTA_LO[round]; s[1] ^= SHA3_IOTA_HI[round];',
    '  }',
    '}',
    END
  );
  return out.join('\n');
}

const generated = generate();
if (process.argv[2] === '--check') {
  const source = readFileSync(new URL('../../src/sha3.ts', import.meta.url), 'utf8');
  const start = source.indexOf(START);
  const end = source.indexOf(END, start);
  assert.notEqual(start, -1, `missing source marker: ${START}`);
  assert.notEqual(end, -1, `missing source marker: ${END}`);
  assert.equal(source.slice(start, end + END.length), generated);
  console.log('src/sha3.ts permutation matches generator');
} else if (process.argv.length === 2) {
  console.log(generated);
} else {
  console.error('Usage: node test/misc/unrolled-sha3.js [--check]');
  process.exitCode = 1;
}
