/** Generates the fixed BLAKE1-512 schedule and fully unrolled BLAKE1-256 compression. */
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';

const B_START = '// BEGIN generated BLAKE1-512 compression';
const B_END = '// END generated BLAKE1-512 compression';
const S_START = '// BEGIN generated BLAKE1-256 compression';
const S_END = '// END generated BLAKE1-256 compression';

// BLAKE submission, section 2.1: ten distinct permutations; later rounds repeat modulo ten.
const OFFICIAL_SIGMA = [
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
  [14, 10, 4, 8, 9, 15, 13, 6, 1, 12, 0, 2, 11, 7, 5, 3],
  [11, 8, 12, 0, 5, 2, 15, 13, 10, 14, 3, 6, 7, 1, 9, 4],
  [7, 9, 3, 1, 13, 12, 11, 14, 2, 6, 5, 10, 4, 0, 15, 8],
  [9, 0, 5, 7, 2, 4, 10, 15, 14, 1, 11, 12, 6, 8, 3, 13],
  [2, 12, 6, 10, 0, 11, 8, 3, 4, 13, 7, 5, 15, 14, 1, 9],
  [12, 5, 1, 15, 14, 13, 4, 10, 0, 7, 6, 3, 9, 2, 8, 11],
  [13, 11, 7, 14, 12, 1, 3, 9, 5, 0, 15, 4, 8, 6, 2, 10],
  [6, 15, 14, 9, 11, 3, 0, 8, 12, 2, 13, 7, 1, 4, 10, 5],
  [10, 2, 8, 4, 7, 6, 1, 5, 15, 11, 9, 14, 3, 12, 13, 0],
];
const EXPECTED_FLAT = [
  0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 14, 10, 4, 8, 9, 15, 13, 6, 1, 12, 0, 2, 11,
  7, 5, 3, 11, 8, 12, 0, 5, 2, 15, 13, 10, 14, 3, 6, 7, 1, 9, 4, 7, 9, 3, 1, 13, 12, 11, 14, 2, 6,
  5, 10, 4, 0, 15, 8, 9, 0, 5, 7, 2, 4, 10, 15, 14, 1, 11, 12, 6, 8, 3, 13, 2, 12, 6, 10, 0, 11, 8,
  3, 4, 13, 7, 5, 15, 14, 1, 9, 12, 5, 1, 15, 14, 13, 4, 10, 0, 7, 6, 3, 9, 2, 8, 11, 13, 11, 7, 14,
  12, 1, 3, 9, 5, 0, 15, 4, 8, 6, 2, 10, 6, 15, 14, 9, 11, 3, 0, 8, 12, 2, 13, 7, 1, 4, 10, 5, 10,
  2, 8, 4, 7, 6, 1, 5, 15, 11, 9, 14, 3, 12, 13, 0,
];
const C32 = [
  0x243f6a88, 0x85a308d3, 0x13198a2e, 0x03707344, 0xa4093822, 0x299f31d0, 0x082efa98, 0xec4e6c89,
  0x452821e6, 0x38d01377, 0xbe5466cf, 0x34e90c6c, 0xc0ac29b7, 0xc97c50dd, 0x3f84d5b5, 0xb5470917,
];
const EXPECTED_C32 = [
  608135816, 2242054355, 320440878, 57701188, 2752067618, 698298832, 137296536, 3964562569,
  1160258022, 953160567, 3193202383, 887688300, 3232508343, 3380367581, 1065670069, 3041331479,
];
const G = [
  [0, 4, 8, 12],
  [1, 5, 9, 13],
  [2, 6, 10, 14],
  [3, 7, 11, 15],
  [0, 5, 10, 15],
  [1, 6, 11, 12],
  [2, 7, 8, 13],
  [3, 4, 9, 14],
];

function schedules(rounds) {
  assert.deepEqual(OFFICIAL_SIGMA.flat(), EXPECTED_FLAT);
  assert.deepEqual(
    C32.map((x) => x >>> 0),
    EXPECTED_C32
  );
  for (const row of OFFICIAL_SIGMA)
    assert.deepEqual(
      [...row].sort((a, b) => a - b),
      OFFICIAL_SIGMA[0]
    );
  return Array.from({ length: rounds }, (_, i) => OFFICIAL_SIGMA[i % 10]);
}

export function generateB() {
  const calls = schedules(16).flatMap((sigma, round) => [
    `    // Round ${round}`,
    ...G.map(
      ([a, b, c, d], i) =>
        `    Gb(${a}, ${b}, ${c}, ${d}, BLAKE512_W, ${sigma[2 * i]}, ${sigma[2 * i + 1]});`
    ),
  ]);
  return `${B_START}
    // Generated by test/misc/unrolled-blake1.js from the BLAKE submission SIGMA. Do not edit.
${calls.join('\n')}
    ${B_END}`;
}

const vn = (n) => `v${String(n).padStart(2, '0')}`;
function half([a, b, c, d], x, companion, second) {
  const A = vn(a),
    B = vn(b),
    C = vn(c),
    D = vn(d),
    rd = second ? 8 : 16,
    rb = second ? 7 : 12;
  return [
    `    ${A} = (${A} + ${B} + (m${x} ^ ${companion})) | 0;`,
    `    ${D} = ((${D} ^ ${A}) >>> ${rd}) | ((${D} ^ ${A}) << ${32 - rd});`,
    `    ${C} = (${C} + ${D}) | 0;`,
    `    ${B} = ((${B} ^ ${C}) >>> ${rb}) | ((${B} ^ ${C}) << ${32 - rb});`,
  ];
}
function sRound(sigma, round) {
  const out = [`    // Round ${round}`];
  for (let i = 0; i < G.length; i++)
    out.push(
      ...half(
        G[i],
        sigma[2 * i],
        `0x${C32[sigma[2 * i + 1]].toString(16).padStart(8, '0')}`,
        false
      ),
      ...half(G[i], sigma[2 * i + 1], `0x${C32[sigma[2 * i]].toString(16).padStart(8, '0')}`, true)
    );
  return out.join('\n');
}
export function generateS() {
  const loads = [];
  for (let i = 0; i < 16; i += 4)
    loads.push(
      `    const ${Array.from({ length: 4 }, (_, j) => `m${i + j} = view.getUint32(offset + ${4 * (i + j)}, false)`).join(', ')};`
    );
  return `${S_START}
  // Generated by test/misc/unrolled-blake1.js from the BLAKE submission SIGMA. Do not edit.
  // prettier-ignore
  compress(view: DataView, offset: number, withLength = true): void {
${loads.join('\n')}
    let v00 = this.v0 | 0, v01 = this.v1 | 0, v02 = this.v2 | 0, v03 = this.v3 | 0;
    let v04 = this.v4 | 0, v05 = this.v5 | 0, v06 = this.v6 | 0, v07 = this.v7 | 0;
    let v08 = this.constants[0] | 0, v09 = this.constants[1] | 0;
    let v10 = this.constants[2] | 0, v11 = this.constants[3] | 0;
    const bits = withLength ? this.length * 8 : 0;
    let v12 = (this.constants[4] ^ (bits >>> 0)) | 0, v13 = (this.constants[5] ^ (bits >>> 0)) | 0;
    let v14 = (this.constants[6] ^ ((bits / 4294967296) | 0)) | 0;
    let v15 = (this.constants[7] ^ ((bits / 4294967296) | 0)) | 0;
${schedules(14).map(sRound).join('\n')}
    this.v0 = (this.v0 ^ v00 ^ v08 ^ this.salt[0]) >>> 0; this.v1 = (this.v1 ^ v01 ^ v09 ^ this.salt[1]) >>> 0;
    this.v2 = (this.v2 ^ v02 ^ v10 ^ this.salt[2]) >>> 0; this.v3 = (this.v3 ^ v03 ^ v11 ^ this.salt[3]) >>> 0;
    this.v4 = (this.v4 ^ v04 ^ v12 ^ this.salt[0]) >>> 0; this.v5 = (this.v5 ^ v05 ^ v13 ^ this.salt[1]) >>> 0;
    this.v6 = (this.v6 ^ v06 ^ v14 ^ this.salt[2]) >>> 0; this.v7 = (this.v7 ^ v07 ^ v15 ^ this.salt[3]) >>> 0;
  }
  ${S_END}`;
}

function checkRegion(source, startMarker, endMarker, generated) {
  const start = source.indexOf(startMarker),
    end = source.indexOf(endMarker, start);
  assert.notEqual(start, -1, `missing ${startMarker}`);
  assert.notEqual(end, -1, `missing ${endMarker}`);
  assert.equal(source.slice(start, end + endMarker.length), generated);
}
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const b = generateB(),
    s = generateS();
  if (process.argv[2] === '--check') {
    const source = readFileSync(new URL('../../src/blake1.ts', import.meta.url), 'utf8');
    checkRegion(source, B_START, B_END, b);
    checkRegion(source, S_START, S_END, s);
    console.log('src/blake1.ts compressions match generator');
  } else if (process.argv.length === 2) console.log(b + '\n\n' + s);
  else {
    console.error('Usage: node test/misc/unrolled-blake1.js [--check]');
    process.exitCode = 1;
  }
}
