/** Generates the scalar-carry Salsa20/8 BlockMix in src/scrypt.ts. */
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const START = '// BEGIN generated scrypt scalar BlockMix';
const END = '// END generated scrypt scalar BlockMix';
const words = Array.from({ length: 16 }, (_, i) => i.toString().padStart(2, '0'));

// RFC 7914 uses Salsa20/8: four column+row double rounds. A tuple is
// [destination, left addend, right addend, left-rotate distance].
const DOUBLE_ROUND = [
  [4, 0, 12, 7],
  [8, 4, 0, 9],
  [12, 8, 4, 13],
  [0, 12, 8, 18],
  [9, 5, 1, 7],
  [13, 9, 5, 9],
  [1, 13, 9, 13],
  [5, 1, 13, 18],
  [14, 10, 6, 7],
  [2, 14, 10, 9],
  [6, 2, 14, 13],
  [10, 6, 2, 18],
  [3, 15, 11, 7],
  [7, 3, 15, 9],
  [11, 7, 3, 13],
  [15, 11, 7, 18],
  [1, 0, 3, 7],
  [2, 1, 0, 9],
  [3, 2, 1, 13],
  [0, 3, 2, 18],
  [6, 5, 4, 7],
  [7, 6, 5, 9],
  [4, 7, 6, 13],
  [5, 4, 7, 18],
  [11, 10, 9, 7],
  [8, 11, 10, 9],
  [9, 8, 11, 13],
  [10, 9, 8, 18],
  [12, 15, 14, 7],
  [13, 12, 15, 9],
  [14, 13, 12, 13],
  [15, 14, 13, 18],
];

const x = (i) => `x${words[i]}`;

function pairs(fn, indent = '  ') {
  const lines = [];
  for (let i = 0; i < 16; i += 2) lines.push(`${indent}${fn(i)} ${fn(i + 1)}`);
  return lines.join('\n');
}

function emitRounds() {
  const operations = DOUBLE_ROUND.map(([dst, a, b, shift]) => {
    const sum = `${x(a)} + ${x(b)} | 0`;
    return `${x(dst)} ^= ((${sum}) << ${shift}) | ((${sum}) >>> ${32 - shift});`;
  });
  const lines = [];
  // Two straight double rounds inside a two-iteration loop gives the four double rounds required
  // by Salsa20/8 while staying below the cross-engine code-size/tiering cliff of full unrolling.
  for (let copy = 0; copy < 2; copy++) {
    for (let i = 0; i < operations.length; i += 2)
      lines.push(`    ${operations[i]} ${operations[i + 1]}`);
  }
  return `  for (let round = 0; round < 4; round += 2) {\n${lines.join('\n')}\n  }`;
}

function emitInputPairs(declare) {
  const lines = [];
  for (let i = 0; i < 16; i += 2) {
    const keyword = declare ? `${declare} ` : '';
    lines.push(
      `  ${keyword}y${words[i]} = s${words[i]} ^ input[ii++], y${words[i + 1]} = s${words[i + 1]} ^ input[ii++];`
    );
  }
  return lines.join('\n');
}

function emitCopy(declare) {
  return [0, 4, 8, 12]
    .map((start, row) => {
      const prefix = row === 0 ? `  ${declare ? `${declare} ` : ''}` : '      ';
      return `${prefix}${words
        .slice(start, start + 4)
        .map((id) => `x${id} = y${id}`)
        .join(', ')}${row === 3 ? ';' : ','}`;
    })
    .join('\n');
}

function emitOutput(where) {
  return pairs(
    (i) => `s${words[i]} = (y${words[i]} + x${words[i]}) | 0; out[${where}++] = s${words[i]};`
  );
}

function generate() {
  const loads = Array.from(
    { length: 8 },
    (_, i) => `  let s${words[2 * i]} = input[si++], s${words[2 * i + 1]} = input[si++];`
  ).join('\n');
  return `${START}
// Generated by test/misc/unrolled-scrypt.js. Do not edit by hand.
// Carrying the chaining block in scalars avoids 15 intermediate 64-byte output reloads at r=8.
// prettier-ignore
function BlockMixScalar(
  input: TArg<Uint32Array>,
  ii: number,
  out: TArg<Uint32Array>,
  oi: number,
  r: number
) {
  let head = oi;
  let tail = oi + 16 * r;
  let si = ii + (2 * r - 1) * 16;
${loads}
  for (let block = 0; block < r; block++) {
${emitInputPairs('let')}
${emitCopy('let')}
${emitRounds()}
${emitOutput('head')}
${emitInputPairs('')}
${emitCopy('')}
${emitRounds()}
${emitOutput('tail')}
  }
}
${END}`;
}

const generated = generate();
if (process.argv[2] === '--check') {
  const source = readFileSync(new URL('../../src/scrypt.ts', import.meta.url), 'utf8');
  const start = source.indexOf(START);
  const end = source.indexOf(END, start);
  assert.notEqual(start, -1, `missing source marker: ${START}`);
  assert.notEqual(end, -1, `missing source marker: ${END}`);
  assert.equal(source.slice(start, end + END.length), generated);
  console.log('src/scrypt.ts scalar BlockMix matches generator');
} else if (process.argv.length === 2) {
  console.log(generated);
} else {
  console.error('Usage: node test/misc/unrolled-scrypt.js [--check]');
  process.exitCode = 1;
}
