/** Generates the portable grouped SHA-1 and MD5 compression cores. */
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';

const SHA1_START = '// BEGIN generated SHA-1 compression';
const SHA1_END = '// END generated SHA-1 compression';
const MD5_START = '// BEGIN generated MD5 compression';
const MD5_END = '// END generated MD5 compression';
const RIPEMD160_START = '// BEGIN generated RIPEMD-160 one-shot compression';
const RIPEMD160_END = '// END generated RIPEMD-160 one-shot compression';

const SHA1_K = [0x5a827999, 0x6ed9eba1, 0x8f1bbcdc, 0xca62c1d6];
const EXPECTED_SHA1_K = [1518500249, 1859775393, 2400959708, 3395469782];
const MD5_SHIFTS = [
  [7, 12, 17, 22],
  [5, 9, 14, 20],
  [4, 11, 16, 23],
  [6, 10, 15, 21],
];
const EXPECTED_MD5_INDEX = [
  0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 1, 6, 11, 0, 5, 10, 15, 4, 9, 14, 3, 8, 13,
  2, 7, 12, 5, 8, 11, 14, 1, 4, 7, 10, 13, 0, 3, 6, 9, 12, 15, 2, 0, 7, 14, 5, 12, 3, 10, 1, 8, 15,
  6, 13, 4, 11, 2, 9,
];
// RFC 1321 T[1..64]. These are asserted against the defining sine formula even though runtime code
// retains its compact generated Array rather than embedding the constants.
const EXPECTED_MD5_K = [
  0xd76aa478, 0xe8c7b756, 0x242070db, 0xc1bdceee, 0xf57c0faf, 0x4787c62a, 0xa8304613, 0xfd469501,
  0x698098d8, 0x8b44f7af, 0xffff5bb1, 0x895cd7be, 0x6b901122, 0xfd987193, 0xa679438e, 0x49b40821,
  0xf61e2562, 0xc040b340, 0x265e5a51, 0xe9b6c7aa, 0xd62f105d, 0x02441453, 0xd8a1e681, 0xe7d3fbc8,
  0x21e1cde6, 0xc33707d6, 0xf4d50d87, 0x455a14ed, 0xa9e3e905, 0xfcefa3f8, 0x676f02d9, 0x8d2a4c8a,
  0xfffa3942, 0x8771f681, 0x6d9d6122, 0xfde5380c, 0xa4beea44, 0x4bdecfa9, 0xf6bb4b60, 0xbebfbc70,
  0x289b7ec6, 0xeaa127fa, 0xd4ef3085, 0x04881d05, 0xd9d4d039, 0xe6db99e5, 0x1fa27cf8, 0xc4ac5665,
  0xf4292244, 0x432aff97, 0xab9423a7, 0xfc93a039, 0x655b59c3, 0x8f0ccc92, 0xffeff47d, 0x85845dd1,
  0x6fa87e4f, 0xfe2ce6e0, 0xa3014314, 0x4e0811a1, 0xf7537e82, 0xbd3af235, 0x2ad7d2bb, 0xeb86d391,
];
const RIPEMD160_KL = [0, 0x5a827999, 0x6ed9eba1, 0x8f1bbcdc, 0xa953fd4e];
const RIPEMD160_KR = [0x50a28be6, 0x5c4dd124, 0x6d703ef3, 0x7a6d76e9, 0];

function checkTables() {
  assert.deepEqual(
    SHA1_K.map((x) => x >>> 0),
    EXPECTED_SHA1_K
  );
  assert.deepEqual(MD5_SHIFTS.flat(), [7, 12, 17, 22, 5, 9, 14, 20, 4, 11, 16, 23, 6, 10, 15, 21]);
  const index = Array.from({ length: 64 }, (_, i) =>
    i < 16 ? i : i < 32 ? (5 * i + 1) & 15 : i < 48 ? (3 * i + 5) & 15 : (7 * i) & 15
  );
  assert.deepEqual(index, EXPECTED_MD5_INDEX);
  const k = Array.from(
    { length: 64 },
    (_, i) => Math.floor(2 ** 32 * Math.abs(Math.sin(i + 1))) >>> 0
  );
  assert.deepEqual(k, EXPECTED_MD5_K);

  // Independently compare the 16-word ring recurrence against an ordinary 80-word expansion.
  const initial = Array.from({ length: 16 }, (_, i) => (0x9e3779b9 * (i + 1)) >>> 0);
  const full = initial.slice();
  for (let i = 16; i < 80; i++)
    full[i] = rotl1(full[i - 3] ^ full[i - 8] ^ full[i - 14] ^ full[i - 16]);
  const ring = initial.slice(),
    expanded = initial.slice();
  for (let i = 16; i < 80; i++) {
    const j = i & 15;
    expanded[i] = ring[j] = rotl1(
      ring[(i - 3) & 15] ^ ring[(i - 8) & 15] ^ ring[(i - 14) & 15] ^ ring[j]
    );
  }
  assert.deepEqual(expanded, full);
}
const rotl1 = (x) => ((x << 1) | (x >>> 31)) >>> 0;

export function generateSHA1() {
  checkTables();
  const phases = [
    [0, 16, '((B & C) ^ (~B & D))', SHA1_K[0], false],
    [16, 20, '((B & C) ^ (~B & D))', SHA1_K[0], true],
    [20, 40, '(B ^ C ^ D)', SHA1_K[1], true],
    [40, 60, '((B & C) ^ (B & D) ^ (C & D))', SHA1_K[2], true],
    [60, 80, '(B ^ C ^ D)', SHA1_K[3], true],
  ];
  const loops = phases.map(([start, end, bool, constant, expand]) => {
    const lines = [`    for (let i = ${start}; i < ${end}; i++) {`];
    let word = 'SHA1_W[i]';
    if (expand) {
      lines.push('      const j = i & 15;');
      lines.push(
        '      const x = SHA1_W[(i - 3) & 15] ^ SHA1_W[(i - 8) & 15] ^ SHA1_W[(i - 14) & 15] ^ SHA1_W[j];'
      );
      lines.push('      const W = (SHA1_W[j] = (x << 1) | (x >>> 31));');
      word = 'W';
    }
    lines.push(
      `      const T = (((A << 5) | (A >>> 27)) + ${bool} + E + 0x${constant.toString(16)} + ${word}) | 0;`
    );
    lines.push('      E = D; D = C; C = (B << 30) | (B >>> 2); B = A; A = T;');
    lines.push('    }');
    return lines.join('\n');
  });
  return `${SHA1_START}
  // Generated by test/misc/unrolled-legacy.js from RFC 3174. Do not edit by hand.
  // prettier-ignore
  protected process(view: DataView, offset: number): void {
    for (let i = 0; i < 16; i++, offset += 4) SHA1_W[i] = view.getUint32(offset, false);
    let { A, B, C, D, E } = this;
${loops.join('\n')}
    this.set((A + this.A) | 0, (B + this.B) | 0, (C + this.C) | 0, (D + this.D) | 0, (E + this.E) | 0);
  }
  ${SHA1_END}`;
}

export function generateMD5() {
  checkTables();
  const groups = [
    {
      start: 0,
      bool: (b, c, d) => `((${b} & ${c}) ^ (~${b} & ${d}))`,
      index: (x) => x,
    },
    {
      start: 16,
      bool: (b, c, d) => `((${d} & ${b}) ^ (~${d} & ${c}))`,
      index: (x) => `(5 * (${x}) + 1) & 15`,
    },
    {
      start: 32,
      bool: (b, c, d) => `(${b} ^ ${c} ^ ${d})`,
      index: (x) => `(3 * (${x}) + 5) & 15`,
    },
    {
      start: 48,
      bool: (b, c, d) => `(${c} ^ (${b} | ~${d}))`,
      index: (x) => `(7 * (${x})) & 15`,
    },
  ];
  const roles = ['A', 'D', 'C', 'B'];
  const loops = groups.map((group, groupIndex) => {
    const lines = [
      `    for (let i = ${group.start}; i < ${group.start + 16}; i += 4) {`,
      '      let F;',
    ];
    for (let q = 0; q < 4; q++) {
      const a = roles[q],
        b = roles[(q + 3) & 3],
        c = roles[(q + 2) & 3],
        d = roles[(q + 1) & 3];
      const x = q ? `i + ${q}` : 'i',
        shift = MD5_SHIFTS[groupIndex][q];
      lines.push(`      F = ${a} + ${group.bool(b, c, d)} + K[${x}] + MD5_W[${group.index(x)}];`);
      lines.push(`      ${a} = (${b} + ((F << ${shift}) | (F >>> ${32 - shift}))) | 0;`);
    }
    lines.push('    }');
    return lines.join('\n');
  });
  return `${MD5_START}
  // Generated by test/misc/unrolled-legacy.js from RFC 1321. Do not edit by hand.
  // prettier-ignore
  protected process(view: DataView, offset: number): void {
    for (let i = 0; i < 16; i++, offset += 4) MD5_W[i] = view.getUint32(offset, true);
    let { A, B, C, D } = this;
${loops.join('\n')}
    this.set((A + this.A) | 0, (B + this.B) | 0, (C + this.C) | 0, (D + this.D) | 0);
  }
  ${MD5_END}`;
}

function ripemd160Bool(group, b, c, d) {
  if (group === 0) return `(${b} ^ ${c} ^ ${d})`;
  if (group === 1) return `((${b} & ${c}) | (~${b} & ${d}))`;
  if (group === 2) return `((${b} | ~${c}) ^ ${d})`;
  if (group === 3) return `((${b} & ${d}) | (${c} & ~${d}))`;
  return `(${b} ^ (${c} | ~${d}))`;
}

export function generateRIPEMD160OneShot() {
  const loops = [];
  for (let group = 0; group < 5; group++) {
    for (const right of [false, true]) {
      const actualGroup = right ? 4 - group : group;
      const [a, b, c, d, e, t] = right
        ? ['ar', 'br', 'cr', 'dr', 'er', 'tr']
        : ['al', 'bl', 'cl', 'dl', 'el', 'tl'];
      const indices = `${right ? 'idxR' : 'idxL'}[${group}]`;
      const shifts = `${right ? 'shiftsR160' : 'shiftsL160'}[${group}]`;
      const constant = (right ? RIPEMD160_KR : RIPEMD160_KL)[group];
      const sum = `${a} + ${ripemd160Bool(actualGroup, b, c, d)} + W[${indices}[i]]${
        constant ? ` + 0x${constant.toString(16)}` : ''
      }`;
      loops.push(`  for (let i = 0; i < 16; i++) {
    const s = ${shifts}[i];
    const x = ${sum};
    const ${t} = ((((x << s) | (x >>> (32 - s))) + ${e}) | 0);
    ${a} = ${e}; ${e} = ${d}; ${d} = (${c} << 10) | (${c} >>> 22); ${c} = ${b}; ${b} = ${t};
  }`);
    }
  }
  return `${RIPEMD160_START}
// Generated by test/misc/unrolled-legacy.js from the RIPEMD-160 specification. Do not edit by hand.
// prettier-ignore
function ripemd160OneShotCore(input: TArg<Uint8Array>, len: number, W: TArg<Uint32Array>): TRet<Uint8Array> {
  for (let i = 0; i < 16; i++) W[i] = 0;
  let pos = 0;
  for (; pos + 4 <= len; pos += 4)
    W[pos >>> 2] = input[pos] | (input[pos + 1] << 8) | (input[pos + 2] << 16) | (input[pos + 3] << 24);
  let word = 0, shift = 0;
  for (; pos < len; pos++, shift += 8) word |= input[pos] << shift;
  W[pos >>> 2] = word | (0x80 << shift);
  W[14] = len * 8;
  let al = 0x67452301 | 0, ar = al, bl = 0xefcdab89 | 0, br = bl,
      cl = 0x98badcfe | 0, cr = cl, dl = 0x10325476 | 0, dr = dl,
      el = 0xc3d2e1f0 | 0, er = el;
${loops.join('\n')}
  const out = new Uint8Array(20);
  setLittle32(out, 0, (0xefcdab89 + cl + dr) | 0);
  setLittle32(out, 4, (0x98badcfe + dl + er) | 0);
  setLittle32(out, 8, (0x10325476 + el + ar) | 0);
  setLittle32(out, 12, (0xc3d2e1f0 + al + br) | 0);
  setLittle32(out, 16, (0x67452301 + bl + cr) | 0);
  return out as TRet<Uint8Array>;
}
${RIPEMD160_END}`;
}

function checkRegion(source, startMarker, endMarker, generated) {
  const start = source.indexOf(startMarker),
    end = source.indexOf(endMarker, start);
  assert.notEqual(start, -1, `missing source marker: ${startMarker}`);
  assert.notEqual(end, -1, `missing source marker: ${endMarker}`);
  assert.equal(source.slice(start, end + endMarker.length), generated);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const sha1 = generateSHA1(),
    md5 = generateMD5(),
    ripemd160 = generateRIPEMD160OneShot();
  if (process.argv[2] === '--check') {
    const source = readFileSync(new URL('../../src/legacy.ts', import.meta.url), 'utf8');
    checkRegion(source, SHA1_START, SHA1_END, sha1);
    checkRegion(source, MD5_START, MD5_END, md5);
    checkRegion(source, RIPEMD160_START, RIPEMD160_END, ripemd160);
    console.log('src/legacy.ts compressions match generator');
  } else if (process.argv.length === 2) console.log(sha1 + '\n\n' + md5 + '\n\n' + ripemd160);
  else {
    console.error('Usage: node test/misc/unrolled-legacy.js [--check]');
    process.exitCode = 1;
  }
}
