/**
 * BLAKE3 tree hash. Can also be used as a MAC, KDF, and XOF.
 *
 * Native BLAKE3 gets most of its headline speed from SIMD and threads. Portable JavaScript has
 * neither explicit SIMD nor implicit worker parallelism, so this implementation specializes the
 * scalar core instead: all seven fixed rounds are unrolled, the message schedule is static, and
 * the 16-word state and message stay in locals. See `audit/blake3.md` for measurements.
 * @module
 */
import { SHA256_IV } from './_md.ts';
import { fromNumH, fromNumL } from './_u64.ts';
import { _BLAKE2 } from './blake2.ts';
// prettier-ignore
import {
  abytes, aexists, anumber, aoutput,
  checkOpts,
  clean,
  copyBytes,
  createHasher, swap32IfBE,
  isLE, u32, u8,
  type CHashXOF,
  type HashXOF,
  type TArg,
  type TRet
} from './utils.ts';

// Constructor-time mode flags (`KEYED_HASH`, `DERIVE_*`) plus per-node tree
// flags (`CHUNK_*`, `PARENT`, `ROOT`).
const B3_Flags = {
  CHUNK_START: 0b1,
  CHUNK_END: 0b10,
  PARENT: 0b100,
  ROOT: 0b1000,
  KEYED_HASH: 0b10000,
  DERIVE_KEY_CONTEXT: 0b100000,
  DERIVE_KEY_MATERIAL: 0b1000000,
} as const;

// Default BLAKE3 IV, cloned from the shared BLAKE2s / SHA-256 IV basis.
const B3_IV = /* @__PURE__ */ SHA256_IV.slice();

// BEGIN generated BLAKE3 compression
// Generated by test/misc/unrolled-blake3.js. Do not edit by hand.
// prettier-ignore
function b3Compress(
  msg: TArg<Uint32Array>,
  offset: number,
  cv: TArg<Uint32Array>,
  t0: number,
  t1: number,
  blockLen: number,
  flags: number,
  out?: TArg<Uint32Array>
) {
  const c0 = cv[0] | 0, c1 = cv[1] | 0, c2 = cv[2] | 0, c3 = cv[3] | 0;
  const c4 = cv[4] | 0, c5 = cv[5] | 0, c6 = cv[6] | 0, c7 = cv[7] | 0;
  const m0 = msg[offset] | 0, m1 = msg[offset + 1] | 0, m2 = msg[offset + 2] | 0, m3 = msg[offset + 3] | 0;
  const m4 = msg[offset + 4] | 0, m5 = msg[offset + 5] | 0, m6 = msg[offset + 6] | 0, m7 = msg[offset + 7] | 0;
  const m8 = msg[offset + 8] | 0, m9 = msg[offset + 9] | 0, m10 = msg[offset + 10] | 0, m11 = msg[offset + 11] | 0;
  const m12 = msg[offset + 12] | 0, m13 = msg[offset + 13] | 0, m14 = msg[offset + 14] | 0, m15 = msg[offset + 15] | 0;
  let v0 = c0, v1 = c1, v2 = c2, v3 = c3, v4 = c4, v5 = c5, v6 = c6, v7 = c7;
  let v8 = 0x6a09e667 | 0, v9 = 0xbb67ae85 | 0, v10 = 0x3c6ef372 | 0, v11 = 0xa54ff53a | 0;
  let v12 = t0 | 0, v13 = t1 | 0, v14 = blockLen | 0, v15 = flags | 0;
  // Round 0: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15
  // columns
  v0 = (v0 + v4 + m0) | 0; v12 ^= v0; v12 = (v12 >>> 16) | (v12 << 16);
  v8 = (v8 + v12) | 0; v4 ^= v8; v4 = (v4 >>> 12) | (v4 << 20);
  v0 = (v0 + v4 + m1) | 0; v12 ^= v0; v12 = (v12 >>> 8) | (v12 << 24);
  v8 = (v8 + v12) | 0; v4 ^= v8; v4 = (v4 >>> 7) | (v4 << 25);
  v1 = (v1 + v5 + m2) | 0; v13 ^= v1; v13 = (v13 >>> 16) | (v13 << 16);
  v9 = (v9 + v13) | 0; v5 ^= v9; v5 = (v5 >>> 12) | (v5 << 20);
  v1 = (v1 + v5 + m3) | 0; v13 ^= v1; v13 = (v13 >>> 8) | (v13 << 24);
  v9 = (v9 + v13) | 0; v5 ^= v9; v5 = (v5 >>> 7) | (v5 << 25);
  v2 = (v2 + v6 + m4) | 0; v14 ^= v2; v14 = (v14 >>> 16) | (v14 << 16);
  v10 = (v10 + v14) | 0; v6 ^= v10; v6 = (v6 >>> 12) | (v6 << 20);
  v2 = (v2 + v6 + m5) | 0; v14 ^= v2; v14 = (v14 >>> 8) | (v14 << 24);
  v10 = (v10 + v14) | 0; v6 ^= v10; v6 = (v6 >>> 7) | (v6 << 25);
  v3 = (v3 + v7 + m6) | 0; v15 ^= v3; v15 = (v15 >>> 16) | (v15 << 16);
  v11 = (v11 + v15) | 0; v7 ^= v11; v7 = (v7 >>> 12) | (v7 << 20);
  v3 = (v3 + v7 + m7) | 0; v15 ^= v3; v15 = (v15 >>> 8) | (v15 << 24);
  v11 = (v11 + v15) | 0; v7 ^= v11; v7 = (v7 >>> 7) | (v7 << 25);
  // diagonals
  v0 = (v0 + v5 + m8) | 0; v15 ^= v0; v15 = (v15 >>> 16) | (v15 << 16);
  v10 = (v10 + v15) | 0; v5 ^= v10; v5 = (v5 >>> 12) | (v5 << 20);
  v0 = (v0 + v5 + m9) | 0; v15 ^= v0; v15 = (v15 >>> 8) | (v15 << 24);
  v10 = (v10 + v15) | 0; v5 ^= v10; v5 = (v5 >>> 7) | (v5 << 25);
  v1 = (v1 + v6 + m10) | 0; v12 ^= v1; v12 = (v12 >>> 16) | (v12 << 16);
  v11 = (v11 + v12) | 0; v6 ^= v11; v6 = (v6 >>> 12) | (v6 << 20);
  v1 = (v1 + v6 + m11) | 0; v12 ^= v1; v12 = (v12 >>> 8) | (v12 << 24);
  v11 = (v11 + v12) | 0; v6 ^= v11; v6 = (v6 >>> 7) | (v6 << 25);
  v2 = (v2 + v7 + m12) | 0; v13 ^= v2; v13 = (v13 >>> 16) | (v13 << 16);
  v8 = (v8 + v13) | 0; v7 ^= v8; v7 = (v7 >>> 12) | (v7 << 20);
  v2 = (v2 + v7 + m13) | 0; v13 ^= v2; v13 = (v13 >>> 8) | (v13 << 24);
  v8 = (v8 + v13) | 0; v7 ^= v8; v7 = (v7 >>> 7) | (v7 << 25);
  v3 = (v3 + v4 + m14) | 0; v14 ^= v3; v14 = (v14 >>> 16) | (v14 << 16);
  v9 = (v9 + v14) | 0; v4 ^= v9; v4 = (v4 >>> 12) | (v4 << 20);
  v3 = (v3 + v4 + m15) | 0; v14 ^= v3; v14 = (v14 >>> 8) | (v14 << 24);
  v9 = (v9 + v14) | 0; v4 ^= v9; v4 = (v4 >>> 7) | (v4 << 25);
  // Round 1: 2, 6, 3, 10, 7, 0, 4, 13, 1, 11, 12, 5, 9, 14, 15, 8
  // columns
  v0 = (v0 + v4 + m2) | 0; v12 ^= v0; v12 = (v12 >>> 16) | (v12 << 16);
  v8 = (v8 + v12) | 0; v4 ^= v8; v4 = (v4 >>> 12) | (v4 << 20);
  v0 = (v0 + v4 + m6) | 0; v12 ^= v0; v12 = (v12 >>> 8) | (v12 << 24);
  v8 = (v8 + v12) | 0; v4 ^= v8; v4 = (v4 >>> 7) | (v4 << 25);
  v1 = (v1 + v5 + m3) | 0; v13 ^= v1; v13 = (v13 >>> 16) | (v13 << 16);
  v9 = (v9 + v13) | 0; v5 ^= v9; v5 = (v5 >>> 12) | (v5 << 20);
  v1 = (v1 + v5 + m10) | 0; v13 ^= v1; v13 = (v13 >>> 8) | (v13 << 24);
  v9 = (v9 + v13) | 0; v5 ^= v9; v5 = (v5 >>> 7) | (v5 << 25);
  v2 = (v2 + v6 + m7) | 0; v14 ^= v2; v14 = (v14 >>> 16) | (v14 << 16);
  v10 = (v10 + v14) | 0; v6 ^= v10; v6 = (v6 >>> 12) | (v6 << 20);
  v2 = (v2 + v6 + m0) | 0; v14 ^= v2; v14 = (v14 >>> 8) | (v14 << 24);
  v10 = (v10 + v14) | 0; v6 ^= v10; v6 = (v6 >>> 7) | (v6 << 25);
  v3 = (v3 + v7 + m4) | 0; v15 ^= v3; v15 = (v15 >>> 16) | (v15 << 16);
  v11 = (v11 + v15) | 0; v7 ^= v11; v7 = (v7 >>> 12) | (v7 << 20);
  v3 = (v3 + v7 + m13) | 0; v15 ^= v3; v15 = (v15 >>> 8) | (v15 << 24);
  v11 = (v11 + v15) | 0; v7 ^= v11; v7 = (v7 >>> 7) | (v7 << 25);
  // diagonals
  v0 = (v0 + v5 + m1) | 0; v15 ^= v0; v15 = (v15 >>> 16) | (v15 << 16);
  v10 = (v10 + v15) | 0; v5 ^= v10; v5 = (v5 >>> 12) | (v5 << 20);
  v0 = (v0 + v5 + m11) | 0; v15 ^= v0; v15 = (v15 >>> 8) | (v15 << 24);
  v10 = (v10 + v15) | 0; v5 ^= v10; v5 = (v5 >>> 7) | (v5 << 25);
  v1 = (v1 + v6 + m12) | 0; v12 ^= v1; v12 = (v12 >>> 16) | (v12 << 16);
  v11 = (v11 + v12) | 0; v6 ^= v11; v6 = (v6 >>> 12) | (v6 << 20);
  v1 = (v1 + v6 + m5) | 0; v12 ^= v1; v12 = (v12 >>> 8) | (v12 << 24);
  v11 = (v11 + v12) | 0; v6 ^= v11; v6 = (v6 >>> 7) | (v6 << 25);
  v2 = (v2 + v7 + m9) | 0; v13 ^= v2; v13 = (v13 >>> 16) | (v13 << 16);
  v8 = (v8 + v13) | 0; v7 ^= v8; v7 = (v7 >>> 12) | (v7 << 20);
  v2 = (v2 + v7 + m14) | 0; v13 ^= v2; v13 = (v13 >>> 8) | (v13 << 24);
  v8 = (v8 + v13) | 0; v7 ^= v8; v7 = (v7 >>> 7) | (v7 << 25);
  v3 = (v3 + v4 + m15) | 0; v14 ^= v3; v14 = (v14 >>> 16) | (v14 << 16);
  v9 = (v9 + v14) | 0; v4 ^= v9; v4 = (v4 >>> 12) | (v4 << 20);
  v3 = (v3 + v4 + m8) | 0; v14 ^= v3; v14 = (v14 >>> 8) | (v14 << 24);
  v9 = (v9 + v14) | 0; v4 ^= v9; v4 = (v4 >>> 7) | (v4 << 25);
  // Round 2: 3, 4, 10, 12, 13, 2, 7, 14, 6, 5, 9, 0, 11, 15, 8, 1
  // columns
  v0 = (v0 + v4 + m3) | 0; v12 ^= v0; v12 = (v12 >>> 16) | (v12 << 16);
  v8 = (v8 + v12) | 0; v4 ^= v8; v4 = (v4 >>> 12) | (v4 << 20);
  v0 = (v0 + v4 + m4) | 0; v12 ^= v0; v12 = (v12 >>> 8) | (v12 << 24);
  v8 = (v8 + v12) | 0; v4 ^= v8; v4 = (v4 >>> 7) | (v4 << 25);
  v1 = (v1 + v5 + m10) | 0; v13 ^= v1; v13 = (v13 >>> 16) | (v13 << 16);
  v9 = (v9 + v13) | 0; v5 ^= v9; v5 = (v5 >>> 12) | (v5 << 20);
  v1 = (v1 + v5 + m12) | 0; v13 ^= v1; v13 = (v13 >>> 8) | (v13 << 24);
  v9 = (v9 + v13) | 0; v5 ^= v9; v5 = (v5 >>> 7) | (v5 << 25);
  v2 = (v2 + v6 + m13) | 0; v14 ^= v2; v14 = (v14 >>> 16) | (v14 << 16);
  v10 = (v10 + v14) | 0; v6 ^= v10; v6 = (v6 >>> 12) | (v6 << 20);
  v2 = (v2 + v6 + m2) | 0; v14 ^= v2; v14 = (v14 >>> 8) | (v14 << 24);
  v10 = (v10 + v14) | 0; v6 ^= v10; v6 = (v6 >>> 7) | (v6 << 25);
  v3 = (v3 + v7 + m7) | 0; v15 ^= v3; v15 = (v15 >>> 16) | (v15 << 16);
  v11 = (v11 + v15) | 0; v7 ^= v11; v7 = (v7 >>> 12) | (v7 << 20);
  v3 = (v3 + v7 + m14) | 0; v15 ^= v3; v15 = (v15 >>> 8) | (v15 << 24);
  v11 = (v11 + v15) | 0; v7 ^= v11; v7 = (v7 >>> 7) | (v7 << 25);
  // diagonals
  v0 = (v0 + v5 + m6) | 0; v15 ^= v0; v15 = (v15 >>> 16) | (v15 << 16);
  v10 = (v10 + v15) | 0; v5 ^= v10; v5 = (v5 >>> 12) | (v5 << 20);
  v0 = (v0 + v5 + m5) | 0; v15 ^= v0; v15 = (v15 >>> 8) | (v15 << 24);
  v10 = (v10 + v15) | 0; v5 ^= v10; v5 = (v5 >>> 7) | (v5 << 25);
  v1 = (v1 + v6 + m9) | 0; v12 ^= v1; v12 = (v12 >>> 16) | (v12 << 16);
  v11 = (v11 + v12) | 0; v6 ^= v11; v6 = (v6 >>> 12) | (v6 << 20);
  v1 = (v1 + v6 + m0) | 0; v12 ^= v1; v12 = (v12 >>> 8) | (v12 << 24);
  v11 = (v11 + v12) | 0; v6 ^= v11; v6 = (v6 >>> 7) | (v6 << 25);
  v2 = (v2 + v7 + m11) | 0; v13 ^= v2; v13 = (v13 >>> 16) | (v13 << 16);
  v8 = (v8 + v13) | 0; v7 ^= v8; v7 = (v7 >>> 12) | (v7 << 20);
  v2 = (v2 + v7 + m15) | 0; v13 ^= v2; v13 = (v13 >>> 8) | (v13 << 24);
  v8 = (v8 + v13) | 0; v7 ^= v8; v7 = (v7 >>> 7) | (v7 << 25);
  v3 = (v3 + v4 + m8) | 0; v14 ^= v3; v14 = (v14 >>> 16) | (v14 << 16);
  v9 = (v9 + v14) | 0; v4 ^= v9; v4 = (v4 >>> 12) | (v4 << 20);
  v3 = (v3 + v4 + m1) | 0; v14 ^= v3; v14 = (v14 >>> 8) | (v14 << 24);
  v9 = (v9 + v14) | 0; v4 ^= v9; v4 = (v4 >>> 7) | (v4 << 25);
  // Round 3: 10, 7, 12, 9, 14, 3, 13, 15, 4, 0, 11, 2, 5, 8, 1, 6
  // columns
  v0 = (v0 + v4 + m10) | 0; v12 ^= v0; v12 = (v12 >>> 16) | (v12 << 16);
  v8 = (v8 + v12) | 0; v4 ^= v8; v4 = (v4 >>> 12) | (v4 << 20);
  v0 = (v0 + v4 + m7) | 0; v12 ^= v0; v12 = (v12 >>> 8) | (v12 << 24);
  v8 = (v8 + v12) | 0; v4 ^= v8; v4 = (v4 >>> 7) | (v4 << 25);
  v1 = (v1 + v5 + m12) | 0; v13 ^= v1; v13 = (v13 >>> 16) | (v13 << 16);
  v9 = (v9 + v13) | 0; v5 ^= v9; v5 = (v5 >>> 12) | (v5 << 20);
  v1 = (v1 + v5 + m9) | 0; v13 ^= v1; v13 = (v13 >>> 8) | (v13 << 24);
  v9 = (v9 + v13) | 0; v5 ^= v9; v5 = (v5 >>> 7) | (v5 << 25);
  v2 = (v2 + v6 + m14) | 0; v14 ^= v2; v14 = (v14 >>> 16) | (v14 << 16);
  v10 = (v10 + v14) | 0; v6 ^= v10; v6 = (v6 >>> 12) | (v6 << 20);
  v2 = (v2 + v6 + m3) | 0; v14 ^= v2; v14 = (v14 >>> 8) | (v14 << 24);
  v10 = (v10 + v14) | 0; v6 ^= v10; v6 = (v6 >>> 7) | (v6 << 25);
  v3 = (v3 + v7 + m13) | 0; v15 ^= v3; v15 = (v15 >>> 16) | (v15 << 16);
  v11 = (v11 + v15) | 0; v7 ^= v11; v7 = (v7 >>> 12) | (v7 << 20);
  v3 = (v3 + v7 + m15) | 0; v15 ^= v3; v15 = (v15 >>> 8) | (v15 << 24);
  v11 = (v11 + v15) | 0; v7 ^= v11; v7 = (v7 >>> 7) | (v7 << 25);
  // diagonals
  v0 = (v0 + v5 + m4) | 0; v15 ^= v0; v15 = (v15 >>> 16) | (v15 << 16);
  v10 = (v10 + v15) | 0; v5 ^= v10; v5 = (v5 >>> 12) | (v5 << 20);
  v0 = (v0 + v5 + m0) | 0; v15 ^= v0; v15 = (v15 >>> 8) | (v15 << 24);
  v10 = (v10 + v15) | 0; v5 ^= v10; v5 = (v5 >>> 7) | (v5 << 25);
  v1 = (v1 + v6 + m11) | 0; v12 ^= v1; v12 = (v12 >>> 16) | (v12 << 16);
  v11 = (v11 + v12) | 0; v6 ^= v11; v6 = (v6 >>> 12) | (v6 << 20);
  v1 = (v1 + v6 + m2) | 0; v12 ^= v1; v12 = (v12 >>> 8) | (v12 << 24);
  v11 = (v11 + v12) | 0; v6 ^= v11; v6 = (v6 >>> 7) | (v6 << 25);
  v2 = (v2 + v7 + m5) | 0; v13 ^= v2; v13 = (v13 >>> 16) | (v13 << 16);
  v8 = (v8 + v13) | 0; v7 ^= v8; v7 = (v7 >>> 12) | (v7 << 20);
  v2 = (v2 + v7 + m8) | 0; v13 ^= v2; v13 = (v13 >>> 8) | (v13 << 24);
  v8 = (v8 + v13) | 0; v7 ^= v8; v7 = (v7 >>> 7) | (v7 << 25);
  v3 = (v3 + v4 + m1) | 0; v14 ^= v3; v14 = (v14 >>> 16) | (v14 << 16);
  v9 = (v9 + v14) | 0; v4 ^= v9; v4 = (v4 >>> 12) | (v4 << 20);
  v3 = (v3 + v4 + m6) | 0; v14 ^= v3; v14 = (v14 >>> 8) | (v14 << 24);
  v9 = (v9 + v14) | 0; v4 ^= v9; v4 = (v4 >>> 7) | (v4 << 25);
  // Round 4: 12, 13, 9, 11, 15, 10, 14, 8, 7, 2, 5, 3, 0, 1, 6, 4
  // columns
  v0 = (v0 + v4 + m12) | 0; v12 ^= v0; v12 = (v12 >>> 16) | (v12 << 16);
  v8 = (v8 + v12) | 0; v4 ^= v8; v4 = (v4 >>> 12) | (v4 << 20);
  v0 = (v0 + v4 + m13) | 0; v12 ^= v0; v12 = (v12 >>> 8) | (v12 << 24);
  v8 = (v8 + v12) | 0; v4 ^= v8; v4 = (v4 >>> 7) | (v4 << 25);
  v1 = (v1 + v5 + m9) | 0; v13 ^= v1; v13 = (v13 >>> 16) | (v13 << 16);
  v9 = (v9 + v13) | 0; v5 ^= v9; v5 = (v5 >>> 12) | (v5 << 20);
  v1 = (v1 + v5 + m11) | 0; v13 ^= v1; v13 = (v13 >>> 8) | (v13 << 24);
  v9 = (v9 + v13) | 0; v5 ^= v9; v5 = (v5 >>> 7) | (v5 << 25);
  v2 = (v2 + v6 + m15) | 0; v14 ^= v2; v14 = (v14 >>> 16) | (v14 << 16);
  v10 = (v10 + v14) | 0; v6 ^= v10; v6 = (v6 >>> 12) | (v6 << 20);
  v2 = (v2 + v6 + m10) | 0; v14 ^= v2; v14 = (v14 >>> 8) | (v14 << 24);
  v10 = (v10 + v14) | 0; v6 ^= v10; v6 = (v6 >>> 7) | (v6 << 25);
  v3 = (v3 + v7 + m14) | 0; v15 ^= v3; v15 = (v15 >>> 16) | (v15 << 16);
  v11 = (v11 + v15) | 0; v7 ^= v11; v7 = (v7 >>> 12) | (v7 << 20);
  v3 = (v3 + v7 + m8) | 0; v15 ^= v3; v15 = (v15 >>> 8) | (v15 << 24);
  v11 = (v11 + v15) | 0; v7 ^= v11; v7 = (v7 >>> 7) | (v7 << 25);
  // diagonals
  v0 = (v0 + v5 + m7) | 0; v15 ^= v0; v15 = (v15 >>> 16) | (v15 << 16);
  v10 = (v10 + v15) | 0; v5 ^= v10; v5 = (v5 >>> 12) | (v5 << 20);
  v0 = (v0 + v5 + m2) | 0; v15 ^= v0; v15 = (v15 >>> 8) | (v15 << 24);
  v10 = (v10 + v15) | 0; v5 ^= v10; v5 = (v5 >>> 7) | (v5 << 25);
  v1 = (v1 + v6 + m5) | 0; v12 ^= v1; v12 = (v12 >>> 16) | (v12 << 16);
  v11 = (v11 + v12) | 0; v6 ^= v11; v6 = (v6 >>> 12) | (v6 << 20);
  v1 = (v1 + v6 + m3) | 0; v12 ^= v1; v12 = (v12 >>> 8) | (v12 << 24);
  v11 = (v11 + v12) | 0; v6 ^= v11; v6 = (v6 >>> 7) | (v6 << 25);
  v2 = (v2 + v7 + m0) | 0; v13 ^= v2; v13 = (v13 >>> 16) | (v13 << 16);
  v8 = (v8 + v13) | 0; v7 ^= v8; v7 = (v7 >>> 12) | (v7 << 20);
  v2 = (v2 + v7 + m1) | 0; v13 ^= v2; v13 = (v13 >>> 8) | (v13 << 24);
  v8 = (v8 + v13) | 0; v7 ^= v8; v7 = (v7 >>> 7) | (v7 << 25);
  v3 = (v3 + v4 + m6) | 0; v14 ^= v3; v14 = (v14 >>> 16) | (v14 << 16);
  v9 = (v9 + v14) | 0; v4 ^= v9; v4 = (v4 >>> 12) | (v4 << 20);
  v3 = (v3 + v4 + m4) | 0; v14 ^= v3; v14 = (v14 >>> 8) | (v14 << 24);
  v9 = (v9 + v14) | 0; v4 ^= v9; v4 = (v4 >>> 7) | (v4 << 25);
  // Round 5: 9, 14, 11, 5, 8, 12, 15, 1, 13, 3, 0, 10, 2, 6, 4, 7
  // columns
  v0 = (v0 + v4 + m9) | 0; v12 ^= v0; v12 = (v12 >>> 16) | (v12 << 16);
  v8 = (v8 + v12) | 0; v4 ^= v8; v4 = (v4 >>> 12) | (v4 << 20);
  v0 = (v0 + v4 + m14) | 0; v12 ^= v0; v12 = (v12 >>> 8) | (v12 << 24);
  v8 = (v8 + v12) | 0; v4 ^= v8; v4 = (v4 >>> 7) | (v4 << 25);
  v1 = (v1 + v5 + m11) | 0; v13 ^= v1; v13 = (v13 >>> 16) | (v13 << 16);
  v9 = (v9 + v13) | 0; v5 ^= v9; v5 = (v5 >>> 12) | (v5 << 20);
  v1 = (v1 + v5 + m5) | 0; v13 ^= v1; v13 = (v13 >>> 8) | (v13 << 24);
  v9 = (v9 + v13) | 0; v5 ^= v9; v5 = (v5 >>> 7) | (v5 << 25);
  v2 = (v2 + v6 + m8) | 0; v14 ^= v2; v14 = (v14 >>> 16) | (v14 << 16);
  v10 = (v10 + v14) | 0; v6 ^= v10; v6 = (v6 >>> 12) | (v6 << 20);
  v2 = (v2 + v6 + m12) | 0; v14 ^= v2; v14 = (v14 >>> 8) | (v14 << 24);
  v10 = (v10 + v14) | 0; v6 ^= v10; v6 = (v6 >>> 7) | (v6 << 25);
  v3 = (v3 + v7 + m15) | 0; v15 ^= v3; v15 = (v15 >>> 16) | (v15 << 16);
  v11 = (v11 + v15) | 0; v7 ^= v11; v7 = (v7 >>> 12) | (v7 << 20);
  v3 = (v3 + v7 + m1) | 0; v15 ^= v3; v15 = (v15 >>> 8) | (v15 << 24);
  v11 = (v11 + v15) | 0; v7 ^= v11; v7 = (v7 >>> 7) | (v7 << 25);
  // diagonals
  v0 = (v0 + v5 + m13) | 0; v15 ^= v0; v15 = (v15 >>> 16) | (v15 << 16);
  v10 = (v10 + v15) | 0; v5 ^= v10; v5 = (v5 >>> 12) | (v5 << 20);
  v0 = (v0 + v5 + m3) | 0; v15 ^= v0; v15 = (v15 >>> 8) | (v15 << 24);
  v10 = (v10 + v15) | 0; v5 ^= v10; v5 = (v5 >>> 7) | (v5 << 25);
  v1 = (v1 + v6 + m0) | 0; v12 ^= v1; v12 = (v12 >>> 16) | (v12 << 16);
  v11 = (v11 + v12) | 0; v6 ^= v11; v6 = (v6 >>> 12) | (v6 << 20);
  v1 = (v1 + v6 + m10) | 0; v12 ^= v1; v12 = (v12 >>> 8) | (v12 << 24);
  v11 = (v11 + v12) | 0; v6 ^= v11; v6 = (v6 >>> 7) | (v6 << 25);
  v2 = (v2 + v7 + m2) | 0; v13 ^= v2; v13 = (v13 >>> 16) | (v13 << 16);
  v8 = (v8 + v13) | 0; v7 ^= v8; v7 = (v7 >>> 12) | (v7 << 20);
  v2 = (v2 + v7 + m6) | 0; v13 ^= v2; v13 = (v13 >>> 8) | (v13 << 24);
  v8 = (v8 + v13) | 0; v7 ^= v8; v7 = (v7 >>> 7) | (v7 << 25);
  v3 = (v3 + v4 + m4) | 0; v14 ^= v3; v14 = (v14 >>> 16) | (v14 << 16);
  v9 = (v9 + v14) | 0; v4 ^= v9; v4 = (v4 >>> 12) | (v4 << 20);
  v3 = (v3 + v4 + m7) | 0; v14 ^= v3; v14 = (v14 >>> 8) | (v14 << 24);
  v9 = (v9 + v14) | 0; v4 ^= v9; v4 = (v4 >>> 7) | (v4 << 25);
  // Round 6: 11, 15, 5, 0, 1, 9, 8, 6, 14, 10, 2, 12, 3, 4, 7, 13
  // columns
  v0 = (v0 + v4 + m11) | 0; v12 ^= v0; v12 = (v12 >>> 16) | (v12 << 16);
  v8 = (v8 + v12) | 0; v4 ^= v8; v4 = (v4 >>> 12) | (v4 << 20);
  v0 = (v0 + v4 + m15) | 0; v12 ^= v0; v12 = (v12 >>> 8) | (v12 << 24);
  v8 = (v8 + v12) | 0; v4 ^= v8; v4 = (v4 >>> 7) | (v4 << 25);
  v1 = (v1 + v5 + m5) | 0; v13 ^= v1; v13 = (v13 >>> 16) | (v13 << 16);
  v9 = (v9 + v13) | 0; v5 ^= v9; v5 = (v5 >>> 12) | (v5 << 20);
  v1 = (v1 + v5 + m0) | 0; v13 ^= v1; v13 = (v13 >>> 8) | (v13 << 24);
  v9 = (v9 + v13) | 0; v5 ^= v9; v5 = (v5 >>> 7) | (v5 << 25);
  v2 = (v2 + v6 + m1) | 0; v14 ^= v2; v14 = (v14 >>> 16) | (v14 << 16);
  v10 = (v10 + v14) | 0; v6 ^= v10; v6 = (v6 >>> 12) | (v6 << 20);
  v2 = (v2 + v6 + m9) | 0; v14 ^= v2; v14 = (v14 >>> 8) | (v14 << 24);
  v10 = (v10 + v14) | 0; v6 ^= v10; v6 = (v6 >>> 7) | (v6 << 25);
  v3 = (v3 + v7 + m8) | 0; v15 ^= v3; v15 = (v15 >>> 16) | (v15 << 16);
  v11 = (v11 + v15) | 0; v7 ^= v11; v7 = (v7 >>> 12) | (v7 << 20);
  v3 = (v3 + v7 + m6) | 0; v15 ^= v3; v15 = (v15 >>> 8) | (v15 << 24);
  v11 = (v11 + v15) | 0; v7 ^= v11; v7 = (v7 >>> 7) | (v7 << 25);
  // diagonals
  v0 = (v0 + v5 + m14) | 0; v15 ^= v0; v15 = (v15 >>> 16) | (v15 << 16);
  v10 = (v10 + v15) | 0; v5 ^= v10; v5 = (v5 >>> 12) | (v5 << 20);
  v0 = (v0 + v5 + m10) | 0; v15 ^= v0; v15 = (v15 >>> 8) | (v15 << 24);
  v10 = (v10 + v15) | 0; v5 ^= v10; v5 = (v5 >>> 7) | (v5 << 25);
  v1 = (v1 + v6 + m2) | 0; v12 ^= v1; v12 = (v12 >>> 16) | (v12 << 16);
  v11 = (v11 + v12) | 0; v6 ^= v11; v6 = (v6 >>> 12) | (v6 << 20);
  v1 = (v1 + v6 + m12) | 0; v12 ^= v1; v12 = (v12 >>> 8) | (v12 << 24);
  v11 = (v11 + v12) | 0; v6 ^= v11; v6 = (v6 >>> 7) | (v6 << 25);
  v2 = (v2 + v7 + m3) | 0; v13 ^= v2; v13 = (v13 >>> 16) | (v13 << 16);
  v8 = (v8 + v13) | 0; v7 ^= v8; v7 = (v7 >>> 12) | (v7 << 20);
  v2 = (v2 + v7 + m4) | 0; v13 ^= v2; v13 = (v13 >>> 8) | (v13 << 24);
  v8 = (v8 + v13) | 0; v7 ^= v8; v7 = (v7 >>> 7) | (v7 << 25);
  v3 = (v3 + v4 + m7) | 0; v14 ^= v3; v14 = (v14 >>> 16) | (v14 << 16);
  v9 = (v9 + v14) | 0; v4 ^= v9; v4 = (v4 >>> 12) | (v4 << 20);
  v3 = (v3 + v4 + m13) | 0; v14 ^= v3; v14 = (v14 >>> 8) | (v14 << 24);
  v9 = (v9 + v14) | 0; v4 ^= v9; v4 = (v4 >>> 7) | (v4 << 25);
  const dst = out || cv;
  dst[0] = v0 ^ v8; dst[1] = v1 ^ v9; dst[2] = v2 ^ v10; dst[3] = v3 ^ v11;
  dst[4] = v4 ^ v12; dst[5] = v5 ^ v13; dst[6] = v6 ^ v14; dst[7] = v7 ^ v15;
  if (out) {
    out[8] = v8 ^ c0; out[9] = v9 ^ c1; out[10] = v10 ^ c2; out[11] = v11 ^ c3;
    out[12] = v12 ^ c4; out[13] = v13 ^ c5; out[14] = v14 ^ c6; out[15] = v15 ^ c7;
  }
}
// END generated BLAKE3 compression

// Reusable scratch for the default one-shot path. It is wiped after every call and
// never contains a key. Reentrant calls get private scratch instead of aliasing the active call.
const B3_ONE_SHOT_SCRATCH = /* @__PURE__ */ new Uint32Array(24 + 8 * 54);
let b3OneShotBusy = false;
const B3_U8_PROTOTYPE = Uint8Array.prototype;
const B3_GET_PROTOTYPE = Object.getPrototypeOf;
const B3_TYPED_ARRAY_PROTOTYPE = B3_GET_PROTOTYPE(B3_U8_PROTOTYPE);
const B3_GET_LENGTH = Object.getOwnPropertyDescriptor(B3_TYPED_ARRAY_PROTOTYPE, 'length')!.get!;
const B3_GET_OFFSET = Object.getOwnPropertyDescriptor(B3_TYPED_ARRAY_PROTOTYPE, 'byteOffset')!.get!;
const B3_GET_BUFFER = Object.getOwnPropertyDescriptor(B3_TYPED_ARRAY_PROTOTYPE, 'buffer')!.get!;

function b3LoadBlock(
  input: TArg<Uint8Array>,
  inputOffset: number,
  blockLen: number,
  words: TArg<Uint32Array>
) {
  words.fill(0, 8, 24);
  let pos = 0;
  for (; pos + 4 <= blockLen; pos += 4) {
    const offset = inputOffset + pos;
    words[8 + (pos >>> 2)] =
      input[offset] |
      (input[offset + 1] << 8) |
      (input[offset + 2] << 16) |
      (input[offset + 3] << 24);
  }
  if (pos < blockLen) {
    const offset = inputOffset + pos;
    let word = 0;
    for (let shift = 0; pos < blockLen; pos++, shift += 8)
      word |= input[inputOffset + pos] << shift;
    words[8 + ((offset - inputOffset) >>> 2)] = word;
  }
}

function b3ResetCV(scratch: TArg<Uint32Array>) {
  scratch[0] = 0x6a09e667;
  scratch[1] = 0xbb67ae85;
  scratch[2] = 0x3c6ef372;
  scratch[3] = 0xa54ff53a;
  scratch[4] = 0x510e527f;
  scratch[5] = 0x9b05688c;
  scratch[6] = 0x1f83d9ab;
  scratch[7] = 0x5be0cd19;
}

// Class construction and cleanup dominate one-shot hashing, especially tiny inputs. Retain the
// same validated public API, but traverse complete chunks with a flat wiped CV stack and keep the
// final Output descriptor available for ROOT compression. Configured calls use the stateful class.
function b3HashOneShot(
  input: TArg<Uint8Array>,
  len: number,
  knownOffset?: number,
  knownBuffer?: ArrayBufferLike
): TRet<Uint8Array> {
  const msg = input;
  const scratch = b3OneShotBusy ? new Uint32Array(24 + 8 * 54) : B3_ONE_SHOT_SCRATCH;
  const shared = scratch === B3_ONE_SHOT_SCRATCH;
  let usedWords = 24;
  if (shared) b3OneShotBusy = true;
  try {
    b3ResetCV(scratch);
    const byteOffset = len >= 64 ? (knownOffset === undefined ? msg.byteOffset : knownOffset) : 0;
    const aligned = isLE && !(byteOffset & 3);
    // Short views make the compressor's zero-padding reads out-of-bounds. SpiderMonkey handles
    // those much worse than decoding the partial block into owned scratch; full blocks still use
    // the zero-copy view.
    const input32 =
      aligned && len >= 64
        ? new Uint32Array(
            knownBuffer === undefined ? msg.buffer : knownBuffer,
            byteOffset,
            Math.floor(len / 4)
          )
        : undefined;
    const chunks = len === 0 ? 1 : Math.ceil(len / 1024);
    let stackLen = 0;
    let offset = 0;

    for (let chunk = 0; chunk < chunks; chunk++) {
      b3ResetCV(scratch);
      const chunkL = fromNumL(chunk);
      const chunkH = fromNumH(chunk);
      const chunkEnd = Math.min(len, offset + 1024);
      let block = 0;
      // Retain each chunk's final block. For the final chunk this preserves the root Output; for
      // earlier chunks it supplies CHUNK_END before the CV is folded into the tree stack.
      while (chunkEnd - offset > 64) {
        const flags = block === 0 ? B3_Flags.CHUNK_START : 0;
        if (input32) b3Compress(input32, offset / 4, scratch, chunkL, chunkH, 64, flags);
        else {
          b3LoadBlock(msg, offset, 64, scratch);
          b3Compress(scratch, 8, scratch, chunkL, chunkH, 64, flags);
        }
        offset += 64;
        block++;
      }

      const blockLen = chunkEnd - offset;
      const chunkFlags = (block === 0 ? B3_Flags.CHUNK_START : 0) | B3_Flags.CHUNK_END;
      if (input32 && blockLen === 64) {
        for (let i = 0; i < 16; i++) scratch[8 + i] = input32[offset / 4 + i] | 0;
      } else b3LoadBlock(msg, offset, blockLen, scratch);
      offset = chunkEnd;

      if (chunk === chunks - 1 && stackLen === 0) {
        b3Compress(scratch, 8, scratch, chunkL, chunkH, blockLen, chunkFlags | B3_Flags.ROOT);
        break;
      }
      b3Compress(scratch, 8, scratch, chunkL, chunkH, blockLen, chunkFlags);

      let total = chunk + 1;
      if (chunk !== chunks - 1)
        while (total % 2 === 0 && stackLen > 0) {
          stackLen--;
          scratch.copyWithin(8, 24 + stackLen * 8, 24 + (stackLen + 1) * 8);
          scratch.copyWithin(16, 0, 8);
          b3ResetCV(scratch);
          b3Compress(scratch, 8, scratch, 0, 0, 64, B3_Flags.PARENT);
          total /= 2;
        }

      if (chunk !== chunks - 1) {
        const stackOffset = 24 + stackLen * 8;
        usedWords = Math.max(usedWords, stackOffset + 8);
        scratch.copyWithin(stackOffset, 0, 8);
        stackLen++;
        continue;
      }

      // Fold the final chunk CV with left subtrees from smallest to largest. The last parent is
      // the root Output descriptor, so apply ROOT during that compression instead of afterwards.
      while (stackLen > 0) {
        stackLen--;
        scratch.copyWithin(8, 24 + stackLen * 8, 24 + (stackLen + 1) * 8);
        scratch.copyWithin(16, 0, 8);
        b3ResetCV(scratch);
        const flags = B3_Flags.PARENT | (stackLen === 0 ? B3_Flags.ROOT : 0);
        b3Compress(scratch, 8, scratch, 0, 0, 64, flags);
      }
    }

    const out = new Uint8Array(32);
    for (let i = 0; i < 8; i++) {
      const word = scratch[i];
      const pos = i * 4;
      out[pos] = word;
      out[pos + 1] = word >>> 8;
      out[pos + 2] = word >>> 16;
      out[pos + 3] = word >>> 24;
    }
    return out as TRet<Uint8Array>;
  } finally {
    // Wipe only the live prefix. Clearing the full maximum-depth stack made tiny hashes
    // disproportionately expensive on SpiderMonkey; every higher word was wiped by the call that
    // last used it.
    scratch.fill(0, 0, usedWords);
    if (shared) b3OneShotBusy = false;
  }
}

/**
 * Ensure to use EITHER `key` OR `context`, not both.
 *
 * * `key`: 32-byte MAC key.
 * * `context`: caller-encoded KDF context bytes. If your protocol defines a
 *   string context, encode it before passing it here.
 *   A good default format for the original context string is
 *   "[application] [commit timestamp] [purpose]".
 */
export type Blake3Opts = {
  /** Desired digest length in bytes. The BLAKE3 spec allows 0..2^64-1 bytes of output. */
  dkLen?: number;
  /** Optional 32-byte MAC key. */
  key?: Uint8Array;
  /** Optional KDF context bytes. */
  context?: Uint8Array;
};

/** Blake3 hash. Can be used as MAC and KDF with caller-encoded context bytes. */
export class _BLAKE3 extends _BLAKE2<_BLAKE3> implements HashXOF<_BLAKE3> {
  readonly canXOF = true;
  private chunkPos = 0; // Position of current block in chunk
  // How many chunks we already have; exact while this stays within
  // JS's safe-integer range.
  private chunksDone = 0;
  private flags = 0 | 0;
  private IV: Uint32Array;
  private state: Uint32Array;
  private stack: Uint32Array[] = [];
  // Output
  private posOut = 0;
  private bufferOut32 = new Uint32Array(16);
  private bufferOut: Uint8Array;
  // Index of output chunk; exact while this stays within JS's
  // safe-integer range.
  private chunkOut = 0;
  private enableXOF = true;

  constructor(opts: Blake3Opts = {}, flags = 0) {
    opts = checkOpts({}, opts);
    super(64, opts.dkLen === undefined ? 32 : opts.dkLen);
    const { key, context } = opts;
    const hasContext = context !== undefined;
    if (key !== undefined) {
      if (hasContext) throw new Error('cannot use both "key" and "context"');
      abytes(key, 32, 'key');
      const k = copyBytes(key);
      this.IV = u32(k);
      swap32IfBE(this.IV);
      this.flags = flags | B3_Flags.KEYED_HASH;
    } else if (hasContext) {
      abytes(context, undefined, 'context');
      const ctx = context;
      const contextKey = new _BLAKE3({ dkLen: 32 }, B3_Flags.DERIVE_KEY_CONTEXT)
        .update(ctx)
        .digest();
      this.IV = u32(contextKey);
      swap32IfBE(this.IV);
      this.flags = flags | B3_Flags.DERIVE_KEY_MATERIAL;
    } else {
      this.IV = B3_IV; // Share the module-private immutable default IV.
      this.flags = flags;
    }
    this.state = this.IV.slice();
    this.bufferOut = u8(this.bufferOut32);
  }
  // _BLAKE2's scalar-state hooks are unused here: BLAKE3 keeps its tree/XOF state in arrays and
  // copies it directly in _cloneInto().
  protected get(): [] {
    return [];
  }
  protected set(): void {}
  // Truncated chunk/parent compression: seed v8..v15 as IV[0..3], t0, t1,
  // block length, and flags, then keep only the first 8 output words.
  private b2Compress(counter: number, flags: number, buf: Uint32Array, bufPos: number = 0) {
    const { state: s, pos } = this;
    const t0 = fromNumL(counter);
    const t1 = fromNumH(counter);
    b3Compress(buf, bufPos, s, t0, t1, pos, flags);
  }
  protected compress(buf: Uint32Array, bufPos: number = 0, isLast: boolean = false): void {
    // Compress last block
    let flags = this.flags;
    if (!this.chunkPos) flags |= B3_Flags.CHUNK_START;
    if (this.chunkPos === 15 || isLast) flags |= B3_Flags.CHUNK_END;
    if (!isLast) this.pos = this.blockLen;
    this.b2Compress(this.chunksDone, flags, buf, bufPos);
    this.chunkPos += 1;
    // If current block is last in chunk (16 blocks), then compress chunks
    if (this.chunkPos === 16 || isLast) {
      let chunk = this.state;
      this.state = this.IV.slice();
      // If not the last one, compress only when there are trailing zeros in chunk counter
      // Chunks are used as a binary tree where the current stack is the path.
      // Zero means the current leaf is finished and can be compressed.
      // 1 (001) - leaf not finished (just push current chunk to stack)
      // 2 (010) - leaf finished at depth=1 (merge with last elm on stack and push back)
      // 3 (011) - last leaf not finished
      // 4 (100) - leafs finished at depth=1 and depth=2
      // Arithmetic preserves high chunk-count bits; bitwise shifts truncate after 2^32 chunks.
      for (let last, chunks = this.chunksDone + 1; isLast || chunks % 2 === 0; chunks /= 2) {
        if (!(last = this.stack.pop())) break;
        this.buffer32.set(last, 0);
        this.buffer32.set(chunk, 8);
        this.pos = this.blockLen;
        this.b2Compress(0, this.flags | B3_Flags.PARENT, this.buffer32, 0);
        chunk = this.state;
        this.state = this.IV.slice();
      }
      this.chunksDone++;
      this.chunkPos = 0;
      this.stack.push(chunk);
    }
    this.pos = 0;
  }
  // Overriding hides _BLAKE2's flat implementation, which would otherwise be inherited
  // and silently miss the tree state (CV stack, chunk counters; get()/set() are stubs here).
  _cloneInto(to?: _BLAKE3): _BLAKE3 {
    const staleOutput = !!to && to.finished && !to.destroyed; // Save before super copies lifecycle.
    to = super._cloneInto(to) as _BLAKE3;
    const { IV, flags, state, chunkPos, posOut, chunkOut, stack, chunksDone } = this;
    to.state.set(state);
    // Clone each CV stack entry by value so extending or destroying the clone
    // cannot alias the source tree state.
    to.stack = stack.map((i) => Uint32Array.from(i));
    if (IV === B3_IV) {
      if (to.IV !== B3_IV) clean(to.IV);
      to.IV = B3_IV; // Share immutable default; configured IVs stay private.
    } else if (to.IV === B3_IV) {
      to.IV = IV.slice();
    } else {
      to.IV.set(IV);
    }
    to.flags = flags;
    to.chunkPos = chunkPos;
    to.chunksDone = chunksDone;
    to.posOut = posOut;
    to.chunkOut = chunkOut;
    to.enableXOF = this.enableXOF;
    if (this.finished) {
      to.bufferOut32.set(this.bufferOut32);
    } else if (staleOutput) {
      clean(to.bufferOut32); // Wipe stale output; finish() overwrites scratch.
    }
    return to;
  }
  destroy(): void {
    this.destroyed = true;
    clean(this.state, this.buffer32, this.bufferOut32);
    if (this.IV !== B3_IV) clean(this.IV);
    clean(...this.stack);
  }
  // Root/XOF compression: rerun the same ROOT inputs with incrementing output
  // counter `t` and materialize all 16 output words.
  // Same as b2Compress, but doesn't modify state and returns 16 u32 array (instead of 8)
  private b2CompressOut() {
    const { state: s, pos, flags, buffer32, bufferOut32: out32 } = this;
    const outCounter = this.chunkOut++;
    const t0 = fromNumL(outCounter);
    const t1 = fromNumH(outCounter);
    swap32IfBE(buffer32);
    b3Compress(buffer32, 0, s, t0, t1, pos, flags, out32);
    swap32IfBE(buffer32);
    swap32IfBE(out32);
    this.posOut = 0;
  }
  protected finish(): void {
    if (this.finished) return;
    this.finished = true;
    // Padding
    this.buffer.fill(0, this.pos);
    // Process last chunk
    let flags = this.flags | B3_Flags.ROOT;
    if (this.stack.length) {
      // Finalize the current chunk first, then rerun the last parent
      // compression as ROOT with t = 0 and b = 64.
      flags |= B3_Flags.PARENT;
      swap32IfBE(this.buffer32);
      this.compress(this.buffer32, 0, true);
      swap32IfBE(this.buffer32);
      this.chunksDone = 0;
      this.pos = this.blockLen;
    } else {
      flags |= (!this.chunkPos ? B3_Flags.CHUNK_START : 0) | B3_Flags.CHUNK_END;
    }
    this.flags = flags;
    this.b2CompressOut();
  }
  private writeInto(out: TArg<Uint8Array>): TRet<Uint8Array> {
    aexists(this, false);
    abytes(out);
    this.finish();
    const { blockLen, bufferOut } = this;
    for (let pos = 0, len = out.length; pos < len; ) {
      if (this.posOut >= blockLen) this.b2CompressOut();
      const take = Math.min(blockLen - this.posOut, len - pos);
      out.set(bufferOut.subarray(this.posOut, this.posOut + take), pos);
      this.posOut += take;
      pos += take;
    }
    return out as TRet<Uint8Array>;
  }
  xofInto(out: TArg<Uint8Array>): TRet<Uint8Array> {
    if (!this.enableXOF) throw new Error('no XOF after digest()');
    return this.writeInto(out);
  }
  xof(bytes: number): TRet<Uint8Array> {
    anumber(bytes);
    return this.xofInto(new Uint8Array(bytes));
  }
  digestInto(out: TArg<Uint8Array>): void {
    aoutput(out, this);
    if (this.finished) throw new Error('digest() was already called');
    this.enableXOF = false;
    // `aoutput(...)` allows oversized buffers; digestInto() must fill only the configured digest.
    this.writeInto(out.length === this.outputLen ? out : out.subarray(0, this.outputLen));
    this.destroy();
  }
  digest(): TRet<Uint8Array> {
    const out = new Uint8Array(this.outputLen);
    this.digestInto(out);
    return out as TRet<Uint8Array>;
  }
}

const blake3Stateful: TRet<CHashXOF<_BLAKE3, Blake3Opts>> = /* @__PURE__ */ createHasher(
  (opts = {}) => new _BLAKE3(opts)
);

const blake3OneShot: any = (msg: TArg<Uint8Array>, opts?: TArg<Blake3Opts>) => {
  if (opts !== undefined) return blake3Stateful(msg, opts);
  const input = abytes(msg);
  const length = input.length;
  if (B3_GET_PROTOTYPE(input) === B3_U8_PROTOTYPE) return b3HashOneShot(input, length);
  const byteOffset = input.byteOffset;
  const buffer = input.buffer;
  // Uint8Array subclasses may override view metadata. Use the fast path only when those values
  // agree with the intrinsic slots; otherwise preserve the stateful implementation's behavior.
  if (
    !ArrayBuffer.isView(input) ||
    B3_GET_LENGTH.call(input) !== length ||
    B3_GET_OFFSET.call(input) !== byteOffset ||
    B3_GET_BUFFER.call(input) !== buffer
  )
    return blake3Stateful(input);
  return b3HashOneShot(input, length, byteOffset, buffer);
};
Object.assign(blake3OneShot, blake3Stateful);
/**
 * BLAKE3 hash function. Can be used as MAC and KDF.
 * @param msg - message that would be hashed
 * @param opts - Optional output, MAC, or KDF configuration. `key` must be
 *   exactly 32 bytes, `context` is caller-encoded bytes, and `dkLen` can be
 *   0..2^64-1 via the XOF-backed output path. See {@link Blake3Opts}.
 * @returns Digest bytes.
 * @example
 * Hash, MAC, or derive key material with BLAKE3.
 * ```ts
 * import { blake3 } from '@noble/hashes/blake3.js';
 * import { utf8ToBytes } from '@noble/hashes/utils.js';
 * const data = new Uint8Array(32);
 * const hash = blake3(data);
 * const mac = blake3(data, { key: new Uint8Array(32) });
 * const kdf = blake3(data, { context: utf8ToBytes('application name') });
 * const xof = blake3(data, { dkLen: 64 });
 * ```
 */
export const blake3: TRet<CHashXOF<_BLAKE3, Blake3Opts>> =
  /* @__PURE__ */ Object.freeze(blake3OneShot);
