/**

SHA1 (RFC 3174), MD5 (RFC 1321), and RIPEMD160 legacy, weak hash functions.
RFC 2286 only covers HMAC-RIPEMD160 wrapper material and test vectors,
not the base RIPEMD-160 compression spec.
Don't use them in a new protocol. What "weak" means:

- Collisions can be made with 2^18 effort in MD5, 2^60 in SHA1, 2^80 in RIPEMD160.
- No practical pre-image attacks (only theoretical, 2^123.4)
- HMAC seems kinda ok: https://www.rfc-editor.org/rfc/rfc6151
 * @module
 */
import { HashMD } from './_md.ts';
import {
  _wrapShortHash,
  type CHash,
  clean,
  createHasher,
  rotl,
  type TArg,
  type TRet,
} from './utils.ts';

/** Initial SHA-1 state from RFC 3174 §6.1. */
const SHA1_IV = /* @__PURE__ */ Uint32Array.from([
  0x67452301, 0xefcdab89, 0x98badcfe, 0x10325476, 0xc3d2e1f0,
]);

// Reusable 16-word rolling SHA-1 message schedule buffer.
const SHA1_W = /* @__PURE__ */ new Uint32Array(16);

/** Internal SHA1 legacy hash class. */
export class _SHA1 extends HashMD<_SHA1> {
  private A = SHA1_IV[0] | 0;
  private B = SHA1_IV[1] | 0;
  private C = SHA1_IV[2] | 0;
  private D = SHA1_IV[3] | 0;
  private E = SHA1_IV[4] | 0;

  constructor() {
    super(64, 20, 8, false);
  }
  protected get(): [number, number, number, number, number] {
    const { A, B, C, D, E } = this;
    return [A, B, C, D, E];
  }
  protected set(A: number, B: number, C: number, D: number, E: number): void {
    this.A = A | 0;
    this.B = B | 0;
    this.C = C | 0;
    this.D = D | 0;
    this.E = E | 0;
  }
  _cloneInto(to?: _SHA1): _SHA1 {
    (to ||= new (this.constructor as any)() as _SHA1).set(...this.get());
    return this._cloneIntoMeta(to);
  }
  // BEGIN generated SHA-1 compression
  // Generated by test/misc/unrolled-legacy.js from RFC 3174. Do not edit by hand.
  // prettier-ignore
  protected process(view: DataView, offset: number): void {
    for (let i = 0; i < 16; i++, offset += 4) SHA1_W[i] = view.getUint32(offset, false);
    let { A, B, C, D, E } = this;
    for (let i = 0; i < 16; i++) {
      const T = (((A << 5) | (A >>> 27)) + ((B & C) ^ (~B & D)) + E + 0x5a827999 + SHA1_W[i]) | 0;
      E = D; D = C; C = (B << 30) | (B >>> 2); B = A; A = T;
    }
    for (let i = 16; i < 20; i++) {
      const j = i & 15;
      const x = SHA1_W[(i - 3) & 15] ^ SHA1_W[(i - 8) & 15] ^ SHA1_W[(i - 14) & 15] ^ SHA1_W[j];
      const W = (SHA1_W[j] = (x << 1) | (x >>> 31));
      const T = (((A << 5) | (A >>> 27)) + ((B & C) ^ (~B & D)) + E + 0x5a827999 + W) | 0;
      E = D; D = C; C = (B << 30) | (B >>> 2); B = A; A = T;
    }
    for (let i = 20; i < 40; i++) {
      const j = i & 15;
      const x = SHA1_W[(i - 3) & 15] ^ SHA1_W[(i - 8) & 15] ^ SHA1_W[(i - 14) & 15] ^ SHA1_W[j];
      const W = (SHA1_W[j] = (x << 1) | (x >>> 31));
      const T = (((A << 5) | (A >>> 27)) + (B ^ C ^ D) + E + 0x6ed9eba1 + W) | 0;
      E = D; D = C; C = (B << 30) | (B >>> 2); B = A; A = T;
    }
    for (let i = 40; i < 60; i++) {
      const j = i & 15;
      const x = SHA1_W[(i - 3) & 15] ^ SHA1_W[(i - 8) & 15] ^ SHA1_W[(i - 14) & 15] ^ SHA1_W[j];
      const W = (SHA1_W[j] = (x << 1) | (x >>> 31));
      const T = (((A << 5) | (A >>> 27)) + ((B & C) ^ (B & D) ^ (C & D)) + E + 0x8f1bbcdc + W) | 0;
      E = D; D = C; C = (B << 30) | (B >>> 2); B = A; A = T;
    }
    for (let i = 60; i < 80; i++) {
      const j = i & 15;
      const x = SHA1_W[(i - 3) & 15] ^ SHA1_W[(i - 8) & 15] ^ SHA1_W[(i - 14) & 15] ^ SHA1_W[j];
      const W = (SHA1_W[j] = (x << 1) | (x >>> 31));
      const T = (((A << 5) | (A >>> 27)) + (B ^ C ^ D) + E + 0xca62c1d6 + W) | 0;
      E = D; D = C; C = (B << 30) | (B >>> 2); B = A; A = T;
    }
    this.set((A + this.A) | 0, (B + this.B) | 0, (C + this.C) | 0, (D + this.D) | 0, (E + this.E) | 0);
  }
  // END generated SHA-1 compression
  protected roundClean(): void {
    clean(SHA1_W);
  }
  destroy(): void {
    // HashMD callers route post-destroy usability through `destroyed`; zeroizing alone still leaves
    // update()/digest() callable on reused instances.
    this.destroyed = true;
    this.set(0, 0, 0, 0, 0);
    clean(this.buffer);
  }
}

/**
 * SHA1 (RFC 3174) legacy hash function. It was cryptographically broken.
 * @param msg - message bytes to hash
 * @param opts - Reserved hash options.
 * @returns Digest bytes.
 * @example
 * Hash a message with SHA1.
 * ```ts
 * sha1(new Uint8Array([97, 98, 99]));
 * ```
 */
export const sha1: TRet<CHash> = /* @__PURE__ */ createHasher(() => new _SHA1());

/** RFC 1321 `T[i]` uses `floor(2^32 * abs(sin(i)))`; this is the shared `2^32` scale factor. */
const p32 = /* @__PURE__ */ Math.pow(2, 32);
/** RFC 1321 `T[1..64]` table. */
const K = /* @__PURE__ */ Array.from({ length: 64 }, (_, i) =>
  Math.floor(p32 * Math.abs(Math.sin(i + 1)))
);

/** MD5 initial state from RFC 1321, stored as 4 u32 words. */
const MD5_IV = /* @__PURE__ */ SHA1_IV.slice(0, 4);

// Reusable 16-word MD5 message block buffer.
const MD5_W = /* @__PURE__ */ new Uint32Array(16);
/** Internal MD5 legacy hash class. */
export class _MD5 extends HashMD<_MD5> {
  private A = MD5_IV[0] | 0;
  private B = MD5_IV[1] | 0;
  private C = MD5_IV[2] | 0;
  private D = MD5_IV[3] | 0;

  constructor() {
    super(64, 16, 8, true);
  }
  protected get(): [number, number, number, number] {
    const { A, B, C, D } = this;
    return [A, B, C, D];
  }
  protected set(A: number, B: number, C: number, D: number): void {
    this.A = A | 0;
    this.B = B | 0;
    this.C = C | 0;
    this.D = D | 0;
  }
  _cloneInto(to?: _MD5): _MD5 {
    (to ||= new (this.constructor as any)() as _MD5).set(...this.get());
    return this._cloneIntoMeta(to);
  }
  // BEGIN generated MD5 compression
  // Generated by test/misc/unrolled-legacy.js from RFC 1321. Do not edit by hand.
  // prettier-ignore
  protected process(view: DataView, offset: number): void {
    for (let i = 0; i < 16; i++, offset += 4) MD5_W[i] = view.getUint32(offset, true);
    let { A, B, C, D } = this;
    for (let i = 0; i < 16; i += 4) {
      let F;
      F = A + ((B & C) ^ (~B & D)) + K[i] + MD5_W[i];
      A = (B + ((F << 7) | (F >>> 25))) | 0;
      F = D + ((A & B) ^ (~A & C)) + K[i + 1] + MD5_W[i + 1];
      D = (A + ((F << 12) | (F >>> 20))) | 0;
      F = C + ((D & A) ^ (~D & B)) + K[i + 2] + MD5_W[i + 2];
      C = (D + ((F << 17) | (F >>> 15))) | 0;
      F = B + ((C & D) ^ (~C & A)) + K[i + 3] + MD5_W[i + 3];
      B = (C + ((F << 22) | (F >>> 10))) | 0;
    }
    for (let i = 16; i < 32; i += 4) {
      let F;
      F = A + ((D & B) ^ (~D & C)) + K[i] + MD5_W[(5 * (i) + 1) & 15];
      A = (B + ((F << 5) | (F >>> 27))) | 0;
      F = D + ((C & A) ^ (~C & B)) + K[i + 1] + MD5_W[(5 * (i + 1) + 1) & 15];
      D = (A + ((F << 9) | (F >>> 23))) | 0;
      F = C + ((B & D) ^ (~B & A)) + K[i + 2] + MD5_W[(5 * (i + 2) + 1) & 15];
      C = (D + ((F << 14) | (F >>> 18))) | 0;
      F = B + ((A & C) ^ (~A & D)) + K[i + 3] + MD5_W[(5 * (i + 3) + 1) & 15];
      B = (C + ((F << 20) | (F >>> 12))) | 0;
    }
    for (let i = 32; i < 48; i += 4) {
      let F;
      F = A + (B ^ C ^ D) + K[i] + MD5_W[(3 * (i) + 5) & 15];
      A = (B + ((F << 4) | (F >>> 28))) | 0;
      F = D + (A ^ B ^ C) + K[i + 1] + MD5_W[(3 * (i + 1) + 5) & 15];
      D = (A + ((F << 11) | (F >>> 21))) | 0;
      F = C + (D ^ A ^ B) + K[i + 2] + MD5_W[(3 * (i + 2) + 5) & 15];
      C = (D + ((F << 16) | (F >>> 16))) | 0;
      F = B + (C ^ D ^ A) + K[i + 3] + MD5_W[(3 * (i + 3) + 5) & 15];
      B = (C + ((F << 23) | (F >>> 9))) | 0;
    }
    for (let i = 48; i < 64; i += 4) {
      let F;
      F = A + (C ^ (B | ~D)) + K[i] + MD5_W[(7 * (i)) & 15];
      A = (B + ((F << 6) | (F >>> 26))) | 0;
      F = D + (B ^ (A | ~C)) + K[i + 1] + MD5_W[(7 * (i + 1)) & 15];
      D = (A + ((F << 10) | (F >>> 22))) | 0;
      F = C + (A ^ (D | ~B)) + K[i + 2] + MD5_W[(7 * (i + 2)) & 15];
      C = (D + ((F << 15) | (F >>> 17))) | 0;
      F = B + (D ^ (C | ~A)) + K[i + 3] + MD5_W[(7 * (i + 3)) & 15];
      B = (C + ((F << 21) | (F >>> 11))) | 0;
    }
    this.set((A + this.A) | 0, (B + this.B) | 0, (C + this.C) | 0, (D + this.D) | 0);
  }
  // END generated MD5 compression
  protected roundClean(): void {
    clean(MD5_W);
  }
  destroy(): void {
    // HashMD callers route post-destroy usability through `destroyed`; zeroizing alone still leaves
    // update()/digest() callable on reused instances.
    this.destroyed = true;
    this.set(0, 0, 0, 0);
    clean(this.buffer);
  }
}

/**
 * MD5 (RFC 1321) legacy hash function. It was cryptographically broken.
 * MD5 architecture is similar to SHA1, with some differences:
 * - Reduced output length: 16 bytes (128 bit) instead of 20
 * - 64 rounds, instead of 80
 * - Little-endian: could be faster, but will require more code
 * - Non-linear index selection: huge speed-up for unroll
 * - Per round constants: more memory accesses, additional speed-up for unroll
 * @param msg - message bytes to hash
 * @param opts - Reserved hash options.
 * @returns Digest bytes.
 * @example
 * Hash a message with MD5.
 * ```ts
 * md5(new Uint8Array([97, 98, 99]));
 * ```
 */
export const md5: TRet<CHash> = /* @__PURE__ */ createHasher(() => new _MD5());

// RIPEMD-160

// Permutation repeatedly applied to derive the later RIPEMD-160 message-order tables.
const Rho160 = /* @__PURE__ */ Uint8Array.from([
  7, 4, 13, 1, 10, 6, 15, 3, 12, 0, 9, 5, 2, 14, 11, 8,
]);
const Id160 = /* @__PURE__ */ (() => Uint8Array.from(new Array(16).fill(0).map((_, i) => i)))();
const Pi160 = /* @__PURE__ */ (() => Id160.map((i) => (9 * i + 5) % 16))();
// Five left/right message-word orderings for the RIPEMD-160 dual-lane rounds.
const idxLR = /* @__PURE__ */ (() => {
  const L = [Id160];
  const R = [Pi160];
  const res = [L, R];
  for (let i = 0; i < 4; i++) for (let j of res) j.push(j[i].map((k) => Rho160[k]));
  return res;
})();
const idxL = /* @__PURE__ */ (() => idxLR[0])();
const idxR = /* @__PURE__ */ (() => idxLR[1])();
// const [idxL, idxR] = idxLR;

// Base per-group shift table before the left/right message-order permutations are applied.
const shifts160 = /* @__PURE__ */ [
  [11, 14, 15, 12, 5, 8, 7, 9, 11, 13, 14, 15, 6, 7, 9, 8],
  [12, 13, 11, 15, 6, 9, 9, 7, 12, 15, 11, 13, 7, 8, 7, 7],
  [13, 15, 14, 11, 7, 7, 6, 8, 13, 14, 13, 12, 5, 5, 6, 9],
  [14, 11, 12, 14, 8, 6, 5, 5, 15, 12, 15, 14, 9, 9, 8, 6],
  [15, 12, 13, 13, 9, 5, 8, 6, 14, 11, 12, 11, 8, 6, 5, 5],
].map((i) => Uint8Array.from(i));
const shiftsL160 = /* @__PURE__ */ idxL.map((idx, i) => idx.map((j) => shifts160[i][j]));
const shiftsR160 = /* @__PURE__ */ idxR.map((idx, i) => idx.map((j) => shifts160[i][j]));
// Five left-lane additive constants for RIPEMD-160.
const Kl160 = /* @__PURE__ */ Uint32Array.from([
  0x00000000, 0x5a827999, 0x6ed9eba1, 0x8f1bbcdc, 0xa953fd4e,
]);
// Five right-lane additive constants for RIPEMD-160.
const Kr160 = /* @__PURE__ */ Uint32Array.from([
  0x50a28be6, 0x5c4dd124, 0x6d703ef3, 0x7a6d76e9, 0x00000000,
]);
// Called `f()` in the spec; valid `group` values are 0..4, and out-of-range
// inputs currently fall through to the group-4 branch.
function ripemd_f(group: number, x: number, y: number, z: number): number {
  if (group === 0) return x ^ y ^ z;
  if (group === 1) return (x & y) | (~x & z);
  if (group === 2) return (x | ~y) ^ z;
  if (group === 3) return (x & z) | (y & ~z);
  return x ^ (y | ~z);
}
// Reusable 16-word RIPEMD-160 message block buffer.
const BUF_160 = /* @__PURE__ */ new Uint32Array(16);

// Short ordinary one-shot calls use disjoint scratch so reentry through the exported stateful
// compressor cannot overwrite either live schedule. Exotic inputs stay on the stateful path.
const RIPEMD160_ONE_SHOT_W = /* @__PURE__ */ new Uint32Array(16);

function setLittle32(out: TArg<Uint8Array>, pos: number, word: number) {
  out[pos] = word;
  out[pos + 1] = word >>> 8;
  out[pos + 2] = word >>> 16;
  out[pos + 3] = word >>> 24;
}

// BEGIN generated RIPEMD-160 one-shot compression
// Generated by test/misc/unrolled-legacy.js from the RIPEMD-160 specification. Do not edit by hand.
// prettier-ignore
function ripemd160OneShotCore(input: TArg<Uint8Array>, len: number, W: TArg<Uint32Array>): TRet<Uint8Array> {
  for (let i = 0; i < 16; i++) W[i] = 0;
  let pos = 0;
  for (; pos + 4 <= len; pos += 4)
    W[pos >>> 2] = input[pos] | (input[pos + 1] << 8) | (input[pos + 2] << 16) | (input[pos + 3] << 24);
  let word = 0, shift = 0;
  for (; pos < len; pos++, shift += 8) word |= input[pos] << shift;
  W[pos >>> 2] = word | (0x80 << shift);
  W[14] = len * 8;
  let al = 0x67452301 | 0, ar = al, bl = 0xefcdab89 | 0, br = bl,
      cl = 0x98badcfe | 0, cr = cl, dl = 0x10325476 | 0, dr = dl,
      el = 0xc3d2e1f0 | 0, er = el;
  for (let i = 0; i < 16; i++) {
    const s = shiftsL160[0][i];
    const x = al + (bl ^ cl ^ dl) + W[idxL[0][i]];
    const tl = ((((x << s) | (x >>> (32 - s))) + el) | 0);
    al = el; el = dl; dl = (cl << 10) | (cl >>> 22); cl = bl; bl = tl;
  }
  for (let i = 0; i < 16; i++) {
    const s = shiftsR160[0][i];
    const x = ar + (br ^ (cr | ~dr)) + W[idxR[0][i]] + 0x50a28be6;
    const tr = ((((x << s) | (x >>> (32 - s))) + er) | 0);
    ar = er; er = dr; dr = (cr << 10) | (cr >>> 22); cr = br; br = tr;
  }
  for (let i = 0; i < 16; i++) {
    const s = shiftsL160[1][i];
    const x = al + ((bl & cl) | (~bl & dl)) + W[idxL[1][i]] + 0x5a827999;
    const tl = ((((x << s) | (x >>> (32 - s))) + el) | 0);
    al = el; el = dl; dl = (cl << 10) | (cl >>> 22); cl = bl; bl = tl;
  }
  for (let i = 0; i < 16; i++) {
    const s = shiftsR160[1][i];
    const x = ar + ((br & dr) | (cr & ~dr)) + W[idxR[1][i]] + 0x5c4dd124;
    const tr = ((((x << s) | (x >>> (32 - s))) + er) | 0);
    ar = er; er = dr; dr = (cr << 10) | (cr >>> 22); cr = br; br = tr;
  }
  for (let i = 0; i < 16; i++) {
    const s = shiftsL160[2][i];
    const x = al + ((bl | ~cl) ^ dl) + W[idxL[2][i]] + 0x6ed9eba1;
    const tl = ((((x << s) | (x >>> (32 - s))) + el) | 0);
    al = el; el = dl; dl = (cl << 10) | (cl >>> 22); cl = bl; bl = tl;
  }
  for (let i = 0; i < 16; i++) {
    const s = shiftsR160[2][i];
    const x = ar + ((br | ~cr) ^ dr) + W[idxR[2][i]] + 0x6d703ef3;
    const tr = ((((x << s) | (x >>> (32 - s))) + er) | 0);
    ar = er; er = dr; dr = (cr << 10) | (cr >>> 22); cr = br; br = tr;
  }
  for (let i = 0; i < 16; i++) {
    const s = shiftsL160[3][i];
    const x = al + ((bl & dl) | (cl & ~dl)) + W[idxL[3][i]] + 0x8f1bbcdc;
    const tl = ((((x << s) | (x >>> (32 - s))) + el) | 0);
    al = el; el = dl; dl = (cl << 10) | (cl >>> 22); cl = bl; bl = tl;
  }
  for (let i = 0; i < 16; i++) {
    const s = shiftsR160[3][i];
    const x = ar + ((br & cr) | (~br & dr)) + W[idxR[3][i]] + 0x7a6d76e9;
    const tr = ((((x << s) | (x >>> (32 - s))) + er) | 0);
    ar = er; er = dr; dr = (cr << 10) | (cr >>> 22); cr = br; br = tr;
  }
  for (let i = 0; i < 16; i++) {
    const s = shiftsL160[4][i];
    const x = al + (bl ^ (cl | ~dl)) + W[idxL[4][i]] + 0xa953fd4e;
    const tl = ((((x << s) | (x >>> (32 - s))) + el) | 0);
    al = el; el = dl; dl = (cl << 10) | (cl >>> 22); cl = bl; bl = tl;
  }
  for (let i = 0; i < 16; i++) {
    const s = shiftsR160[4][i];
    const x = ar + (br ^ cr ^ dr) + W[idxR[4][i]];
    const tr = ((((x << s) | (x >>> (32 - s))) + er) | 0);
    ar = er; er = dr; dr = (cr << 10) | (cr >>> 22); cr = br; br = tr;
  }
  const out = new Uint8Array(20);
  setLittle32(out, 0, (0xefcdab89 + cl + dr) | 0);
  setLittle32(out, 4, (0x98badcfe + dl + er) | 0);
  setLittle32(out, 8, (0x10325476 + el + ar) | 0);
  setLittle32(out, 12, (0xc3d2e1f0 + al + br) | 0);
  setLittle32(out, 16, (0x67452301 + bl + cr) | 0);
  return out as TRet<Uint8Array>;
}
// END generated RIPEMD-160 one-shot compression

function ripemd160HashOneShot(input: TArg<Uint8Array>, len: number): TRet<Uint8Array> {
  try {
    return ripemd160OneShotCore(input, len, RIPEMD160_ONE_SHOT_W);
  } finally {
    // Avoid a dynamically dispatched fill() while scratch is leased: indexed writes on this
    // private typed array cannot invoke user code or reenter hashing.
    for (let i = 0; i < 16; i++) RIPEMD160_ONE_SHOT_W[i] = 0;
  }
}
/**
 * Internal RIPEMD-160 legacy hash class.
 * RFC 2286 only adds HMAC-RIPEMD160 material, not the core hash specification.
 */
export class _RIPEMD160 extends HashMD<_RIPEMD160> {
  private h0 = 0x67452301 | 0;
  private h1 = 0xefcdab89 | 0;
  private h2 = 0x98badcfe | 0;
  private h3 = 0x10325476 | 0;
  private h4 = 0xc3d2e1f0 | 0;

  constructor() {
    super(64, 20, 8, true);
  }
  protected get(): [number, number, number, number, number] {
    const { h0, h1, h2, h3, h4 } = this;
    return [h0, h1, h2, h3, h4];
  }
  protected set(h0: number, h1: number, h2: number, h3: number, h4: number): void {
    this.h0 = h0 | 0;
    this.h1 = h1 | 0;
    this.h2 = h2 | 0;
    this.h3 = h3 | 0;
    this.h4 = h4 | 0;
  }
  _cloneInto(to?: _RIPEMD160): _RIPEMD160 {
    (to ||= new (this.constructor as any)() as _RIPEMD160).set(...this.get());
    return this._cloneIntoMeta(to);
  }
  protected process(view: DataView, offset: number): void {
    for (let i = 0; i < 16; i++, offset += 4) BUF_160[i] = view.getUint32(offset, true);
    // prettier-ignore
    let al = this.h0 | 0, ar = al,
        bl = this.h1 | 0, br = bl,
        cl = this.h2 | 0, cr = cl,
        dl = this.h3 | 0, dr = dl,
        el = this.h4 | 0, er = el;

    // Instead of iterating 0 to 80, we split it into 5 groups
    // And use the groups in constants, functions, etc. Much simpler
    for (let group = 0; group < 5; group++) {
      const rGroup = 4 - group;
      const hbl = Kl160[group], hbr = Kr160[group]; // prettier-ignore
      const rl = idxL[group], rr = idxR[group]; // prettier-ignore
      const sl = shiftsL160[group], sr = shiftsR160[group]; // prettier-ignore
      for (let i = 0; i < 16; i++) {
        const tl = (rotl(al + ripemd_f(group, bl, cl, dl) + BUF_160[rl[i]] + hbl, sl[i]) + el) | 0;
        al = el, el = dl, dl = rotl(cl, 10) | 0, cl = bl, bl = tl; // prettier-ignore
      }
      // 2 loops are 10% faster
      for (let i = 0; i < 16; i++) {
        const tr = (rotl(ar + ripemd_f(rGroup, br, cr, dr) + BUF_160[rr[i]] + hbr, sr[i]) + er) | 0;
        ar = er, er = dr, dr = rotl(cr, 10) | 0, cr = br, br = tr; // prettier-ignore
      }
    }
    // Add the compressed chunk to the current hash value
    // Final recombination cross-adds the left/right lane accumulators into the next h0..h4 order.
    this.set(
      (this.h1 + cl + dr) | 0,
      (this.h2 + dl + er) | 0,
      (this.h3 + el + ar) | 0,
      (this.h4 + al + br) | 0,
      (this.h0 + bl + cr) | 0
    );
  }
  protected roundClean(): void {
    clean(BUF_160);
  }
  destroy(): void {
    this.destroyed = true;
    clean(this.buffer);
    this.set(0, 0, 0, 0, 0);
  }
}

const ripemd160Stateful: TRet<CHash> = /* @__PURE__ */ createHasher(() => new _RIPEMD160());

function ripemd160Wrap(stateful: TArg<TRet<CHash>>): TRet<CHash> {
  // One-block padding ends at 55 bytes. Longer inputs keep the existing streaming compressor;
  // the direct specialization is intentionally bounded to avoid the JSC giant-function cliff.
  return _wrapShortHash(stateful, 55, ripemd160HashOneShot);
}

/**
 * RIPEMD-160 - a legacy hash function from 1990s.
 * RFC 2286 only covers HMAC-RIPEMD160 test material; the links below point
 * at the base RIPEMD-160 references.
 * * {@link https://homes.esat.kuleuven.be/~bosselae/ripemd160.html}
 * * {@link https://homes.esat.kuleuven.be/~bosselae/ripemd160/pdf/AB-9601/AB-9601.pdf}
 * @param msg - message bytes to hash
 * @param opts - Reserved hash options.
 * @returns Digest bytes.
 * @example
 * Hash a message with RIPEMD-160.
 * ```ts
 * ripemd160(new Uint8Array([97, 98, 99]));
 * ```
 */
export const ripemd160: TRet<CHash> = /* @__PURE__ */ ripemd160Wrap(ripemd160Stateful);
