/**
 * SHA3 (keccak) hash function, based on a new "Sponge function" design.
 * Different from older hashes, the internal state is bigger than output size.
 *
 * Check out
 * {@link https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.202.pdf | FIPS-202},
 * {@link https://keccak.team/keccak.html | Website}, and
 * {@link https://crypto.stackexchange.com/q/15727 | the differences between
 * SHA-3 and Keccak}.
 *
 * Check out `sha3-addons` module for cSHAKE, k12, and others.
 * @module
 */
// prettier-ignore
import {
  _wrapShortHash, abool, abytes, aexists, anumber, aoutput,
  checkOpts,
  clean, createHasher,
  oidNist,
  swap32IfBE,
  u32,
  type CHash, type CHashXOF,
  type Hash,
  type HashInfo,
  type HashXOF,
  type TArg,
  type TRet
} from './utils.ts';

// BEGIN generated SHA3 permutation
// Generated by test/misc/unrolled-sha3.js. Do not edit by hand.
// prettier-ignore
const SHA3_IOTA_LO = /* @__PURE__ */ Uint32Array.from([0x00000001, 0x00008082, 0x0000808a, 0x80008000, 0x0000808b, 0x80000001, 0x80008081, 0x00008009, 0x0000008a, 0x00000088, 0x80008009, 0x8000000a, 0x8000808b, 0x0000008b, 0x00008089, 0x00008003, 0x00008002, 0x00000080, 0x0000800a, 0x8000000a, 0x80008081, 0x00008080, 0x80000001, 0x80008008]);
// prettier-ignore
const SHA3_IOTA_HI = /* @__PURE__ */ Uint32Array.from([0x00000000, 0x00000000, 0x80000000, 0x80000000, 0x00000000, 0x00000000, 0x80000000, 0x80000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x80000000, 0x80000000, 0x80000000, 0x80000000, 0x80000000, 0x00000000, 0x80000000, 0x80000000, 0x80000000, 0x00000000, 0x80000000]);

// prettier-ignore
function keccakP1600(s: TArg<Uint32Array>, rounds: number): void {
  let h: number, l: number, sh: number, sl: number;
  let b0: number, b1: number, b2: number, b3: number, b4: number;
  let b5: number, b6: number, b7: number, b8: number, b9: number;
  for (let round = 24 - rounds; round < 24; round++) {
    // Theta θ
    b0 = s[0] ^ s[10] ^ s[20] ^ s[30] ^ s[40];
    b1 = s[1] ^ s[11] ^ s[21] ^ s[31] ^ s[41];
    b2 = s[2] ^ s[12] ^ s[22] ^ s[32] ^ s[42];
    b3 = s[3] ^ s[13] ^ s[23] ^ s[33] ^ s[43];
    b4 = s[4] ^ s[14] ^ s[24] ^ s[34] ^ s[44];
    b5 = s[5] ^ s[15] ^ s[25] ^ s[35] ^ s[45];
    b6 = s[6] ^ s[16] ^ s[26] ^ s[36] ^ s[46];
    b7 = s[7] ^ s[17] ^ s[27] ^ s[37] ^ s[47];
    b8 = s[8] ^ s[18] ^ s[28] ^ s[38] ^ s[48];
    b9 = s[9] ^ s[19] ^ s[29] ^ s[39] ^ s[49];
    h = ((b2 << 1) | (b3 >>> 31)) ^ b8;
    l = ((b3 << 1) | (b2 >>> 31)) ^ b9;
    s[0] ^= h; s[1] ^= l;
    s[10] ^= h; s[11] ^= l;
    s[20] ^= h; s[21] ^= l;
    s[30] ^= h; s[31] ^= l;
    s[40] ^= h; s[41] ^= l;
    h = ((b4 << 1) | (b5 >>> 31)) ^ b0;
    l = ((b5 << 1) | (b4 >>> 31)) ^ b1;
    s[2] ^= h; s[3] ^= l;
    s[12] ^= h; s[13] ^= l;
    s[22] ^= h; s[23] ^= l;
    s[32] ^= h; s[33] ^= l;
    s[42] ^= h; s[43] ^= l;
    h = ((b6 << 1) | (b7 >>> 31)) ^ b2;
    l = ((b7 << 1) | (b6 >>> 31)) ^ b3;
    s[4] ^= h; s[5] ^= l;
    s[14] ^= h; s[15] ^= l;
    s[24] ^= h; s[25] ^= l;
    s[34] ^= h; s[35] ^= l;
    s[44] ^= h; s[45] ^= l;
    h = ((b8 << 1) | (b9 >>> 31)) ^ b4;
    l = ((b9 << 1) | (b8 >>> 31)) ^ b5;
    s[6] ^= h; s[7] ^= l;
    s[16] ^= h; s[17] ^= l;
    s[26] ^= h; s[27] ^= l;
    s[36] ^= h; s[37] ^= l;
    s[46] ^= h; s[47] ^= l;
    h = ((b0 << 1) | (b1 >>> 31)) ^ b6;
    l = ((b1 << 1) | (b0 >>> 31)) ^ b7;
    s[8] ^= h; s[9] ^= l;
    s[18] ^= h; s[19] ^= l;
    s[28] ^= h; s[29] ^= l;
    s[38] ^= h; s[39] ^= l;
    s[48] ^= h; s[49] ^= l;
    // Rho ρ and Pi π
    sh = s[2]; sl = s[3];
    h = ((sh << 1) | (sl >>> 31)); l = ((sl << 1) | (sh >>> 31));
    sh = s[20]; sl = s[21]; s[20] = h; s[21] = l;
    h = ((sh << 3) | (sl >>> 29)); l = ((sl << 3) | (sh >>> 29));
    sh = s[14]; sl = s[15]; s[14] = h; s[15] = l;
    h = ((sh << 6) | (sl >>> 26)); l = ((sl << 6) | (sh >>> 26));
    sh = s[22]; sl = s[23]; s[22] = h; s[23] = l;
    h = ((sh << 10) | (sl >>> 22)); l = ((sl << 10) | (sh >>> 22));
    sh = s[34]; sl = s[35]; s[34] = h; s[35] = l;
    h = ((sh << 15) | (sl >>> 17)); l = ((sl << 15) | (sh >>> 17));
    sh = s[36]; sl = s[37]; s[36] = h; s[37] = l;
    h = ((sh << 21) | (sl >>> 11)); l = ((sl << 21) | (sh >>> 11));
    sh = s[6]; sl = s[7]; s[6] = h; s[7] = l;
    h = ((sh << 28) | (sl >>> 4)); l = ((sl << 28) | (sh >>> 4));
    sh = s[10]; sl = s[11]; s[10] = h; s[11] = l;
    h = ((sl << 4) | (sh >>> 28)); l = ((sh << 4) | (sl >>> 28));
    sh = s[32]; sl = s[33]; s[32] = h; s[33] = l;
    h = ((sl << 13) | (sh >>> 19)); l = ((sh << 13) | (sl >>> 19));
    sh = s[16]; sl = s[17]; s[16] = h; s[17] = l;
    h = ((sl << 23) | (sh >>> 9)); l = ((sh << 23) | (sl >>> 9));
    sh = s[42]; sl = s[43]; s[42] = h; s[43] = l;
    h = ((sh << 2) | (sl >>> 30)); l = ((sl << 2) | (sh >>> 30));
    sh = s[48]; sl = s[49]; s[48] = h; s[49] = l;
    h = ((sh << 14) | (sl >>> 18)); l = ((sl << 14) | (sh >>> 18));
    sh = s[8]; sl = s[9]; s[8] = h; s[9] = l;
    h = ((sh << 27) | (sl >>> 5)); l = ((sl << 27) | (sh >>> 5));
    sh = s[30]; sl = s[31]; s[30] = h; s[31] = l;
    h = ((sl << 9) | (sh >>> 23)); l = ((sh << 9) | (sl >>> 23));
    sh = s[46]; sl = s[47]; s[46] = h; s[47] = l;
    h = ((sl << 24) | (sh >>> 8)); l = ((sh << 24) | (sl >>> 8));
    sh = s[38]; sl = s[39]; s[38] = h; s[39] = l;
    h = ((sh << 8) | (sl >>> 24)); l = ((sl << 8) | (sh >>> 24));
    sh = s[26]; sl = s[27]; s[26] = h; s[27] = l;
    h = ((sh << 25) | (sl >>> 7)); l = ((sl << 25) | (sh >>> 7));
    sh = s[24]; sl = s[25]; s[24] = h; s[25] = l;
    h = ((sl << 11) | (sh >>> 21)); l = ((sh << 11) | (sl >>> 21));
    sh = s[4]; sl = s[5]; s[4] = h; s[5] = l;
    h = ((sl << 30) | (sh >>> 2)); l = ((sh << 30) | (sl >>> 2));
    sh = s[40]; sl = s[41]; s[40] = h; s[41] = l;
    h = ((sh << 18) | (sl >>> 14)); l = ((sl << 18) | (sh >>> 14));
    sh = s[28]; sl = s[29]; s[28] = h; s[29] = l;
    h = ((sl << 7) | (sh >>> 25)); l = ((sh << 7) | (sl >>> 25));
    sh = s[44]; sl = s[45]; s[44] = h; s[45] = l;
    h = ((sl << 29) | (sh >>> 3)); l = ((sh << 29) | (sl >>> 3));
    sh = s[18]; sl = s[19]; s[18] = h; s[19] = l;
    h = ((sh << 20) | (sl >>> 12)); l = ((sl << 20) | (sh >>> 12));
    sh = s[12]; sl = s[13]; s[12] = h; s[13] = l;
    h = ((sl << 12) | (sh >>> 20)); l = ((sh << 12) | (sl >>> 20));
    sh = s[2]; sl = s[3]; s[2] = h; s[3] = l;
    // Chi χ
    b0 = s[0]; b1 = s[1]; b2 = s[2]; b3 = s[3];
    s[0] ^= ~s[2] & s[4]; s[1] ^= ~s[3] & s[5];
    s[2] ^= ~s[4] & s[6]; s[3] ^= ~s[5] & s[7];
    s[4] ^= ~s[6] & s[8]; s[5] ^= ~s[7] & s[9];
    s[6] ^= ~s[8] & b0; s[7] ^= ~s[9] & b1;
    s[8] ^= ~b0 & b2; s[9] ^= ~b1 & b3;
    b0 = s[10]; b1 = s[11]; b2 = s[12]; b3 = s[13];
    s[10] ^= ~s[12] & s[14]; s[11] ^= ~s[13] & s[15];
    s[12] ^= ~s[14] & s[16]; s[13] ^= ~s[15] & s[17];
    s[14] ^= ~s[16] & s[18]; s[15] ^= ~s[17] & s[19];
    s[16] ^= ~s[18] & b0; s[17] ^= ~s[19] & b1;
    s[18] ^= ~b0 & b2; s[19] ^= ~b1 & b3;
    b0 = s[20]; b1 = s[21]; b2 = s[22]; b3 = s[23];
    s[20] ^= ~s[22] & s[24]; s[21] ^= ~s[23] & s[25];
    s[22] ^= ~s[24] & s[26]; s[23] ^= ~s[25] & s[27];
    s[24] ^= ~s[26] & s[28]; s[25] ^= ~s[27] & s[29];
    s[26] ^= ~s[28] & b0; s[27] ^= ~s[29] & b1;
    s[28] ^= ~b0 & b2; s[29] ^= ~b1 & b3;
    b0 = s[30]; b1 = s[31]; b2 = s[32]; b3 = s[33];
    s[30] ^= ~s[32] & s[34]; s[31] ^= ~s[33] & s[35];
    s[32] ^= ~s[34] & s[36]; s[33] ^= ~s[35] & s[37];
    s[34] ^= ~s[36] & s[38]; s[35] ^= ~s[37] & s[39];
    s[36] ^= ~s[38] & b0; s[37] ^= ~s[39] & b1;
    s[38] ^= ~b0 & b2; s[39] ^= ~b1 & b3;
    b0 = s[40]; b1 = s[41]; b2 = s[42]; b3 = s[43];
    s[40] ^= ~s[42] & s[44]; s[41] ^= ~s[43] & s[45];
    s[42] ^= ~s[44] & s[46]; s[43] ^= ~s[45] & s[47];
    s[44] ^= ~s[46] & s[48]; s[45] ^= ~s[47] & s[49];
    s[46] ^= ~s[48] & b0; s[47] ^= ~s[49] & b1;
    s[48] ^= ~b0 & b2; s[49] ^= ~b1 & b3;
    // Iota ι
    s[0] ^= SHA3_IOTA_LO[round]; s[1] ^= SHA3_IOTA_HI[round];
  }
}
// END generated SHA3 permutation

/**
 * `keccakf1600` internal permutation, additionally allows adjusting the round count.
 * @param s - 5x5 Keccak state encoded as 25 lanes split into 50 uint32 words
 *   in this file's local little-endian lane-word order
 * @param rounds - number of rounds to execute
 * @throws On wrong argument types. {@link TypeError}
 * @throws On wrong argument ranges or values. {@link RangeError}
 * @throws If `rounds` is outside the supported `1..24` range. {@link Error}
 * @example
 * Permute a Keccak state with the default 24 rounds.
 * ```ts
 * keccakP(new Uint32Array(50));
 * ```
 */
export function keccakP(s: TArg<Uint32Array>, rounds: number = 24): void {
  if (!(s instanceof Uint32Array))
    throw new TypeError('"s" expected Uint32Array(50), got type=' + typeof s);
  if (s.length !== 50) throw new RangeError('"s" expected Uint32Array(50), got length=' + s.length);
  anumber(rounds, 'rounds');
  if (rounds < 1 || rounds > 24) throw new Error('"rounds" expected integer 1..24');
  keccakP1600(s, rounds);
}

/**
 * Keccak sponge function.
 * @param blockLen - absorb/squeeze rate in bytes
 * @param suffix - domain separation suffix byte
 * @param outputLen - default digest length in bytes. This base sponge only
 *   requires a non-negative integer; wrappers that need positive output
 *   lengths must enforce that themselves.
 * @param enableXOF - whether XOF output is allowed
 * @param rounds - number of Keccak-f rounds
 * @example
 * Build a sponge state, absorb bytes, then finalize a digest.
 * ```ts
 * const hash = new Keccak(136, 0x06, 32);
 * hash.update(new Uint8Array([1, 2, 3]));
 * hash.digest();
 * ```
 */
export class Keccak implements Hash<Keccak>, HashXOF<Keccak> {
  protected state: Uint8Array;
  protected pos = 0;
  protected posOut = 0;
  protected finished = false;
  protected state32: Uint32Array;
  protected destroyed = false;

  public blockLen: number;
  public suffix: number;
  public outputLen: number;
  public canXOF: boolean;
  protected enableXOF = false;
  protected rounds: number;

  // NOTE: we accept arguments in bytes instead of bits here.
  constructor(
    blockLen: number,
    suffix: number,
    outputLen: number,
    enableXOF = false,
    rounds: number = 24
  ) {
    anumber(blockLen, 'blockLen');
    anumber(suffix, 'suffix');
    anumber(rounds, 'rounds');
    abool(enableXOF, 'enableXOF');
    this.blockLen = blockLen;
    this.suffix = suffix;
    this.outputLen = outputLen;
    this.enableXOF = enableXOF;
    this.canXOF = enableXOF;
    this.rounds = rounds;
    // Can be passed from user as dkLen
    anumber(outputLen, 'outputLen');
    // Only keccak-f1600 is supported: 1600 bits (5x5 matrix of 64bit) === 200 bytes of state.
    if (!(0 < blockLen && blockLen < 200)) throw new Error('"blockLen" must be 1..199');
    this.state = new Uint8Array(200);
    this.state32 = u32(this.state);
  }
  clone(): Keccak {
    return this._cloneInto();
  }
  protected keccak(): void {
    swap32IfBE(this.state32);
    keccakP(this.state32, this.rounds);
    swap32IfBE(this.state32);
    this.posOut = 0;
    this.pos = 0;
  }
  update(data: TArg<Uint8Array>): this {
    aexists(this);
    abytes(data);
    const { blockLen, state, state32 } = this;
    const len = data.length;
    // Absorb full blocks with u32 XORs when both sides are 4-byte aligned.
    // XOR of same-position words equals XOR of same-position bytes, so this is endianness-safe.
    const canUseU32 = blockLen % 4 === 0 && data.byteOffset % 4 === 0;
    const blockLen32 = blockLen / 4;
    const data32 = canUseU32 && len >= blockLen ? u32(data) : undefined;
    for (let pos = 0; pos < len; ) {
      if (data32 !== undefined && this.pos === 0 && pos % 4 === 0 && len - pos >= blockLen) {
        for (let i = 0, o = pos / 4; i < blockLen32; i++) state32[i] ^= data32[o + i];
        pos += blockLen;
        // Subclasses (_KeccakPRG) read `this.pos` inside their `keccak()` override,
        // so it must reflect the fully-absorbed block before the permutation fires.
        this.pos = blockLen;
        this.keccak();
        continue;
      }
      const take = Math.min(blockLen - this.pos, len - pos);
      for (let i = 0; i < take; i++) state[this.pos++] ^= data[pos++];
      if (this.pos === blockLen) this.keccak();
    }
    return this;
  }
  protected finish(): void {
    if (this.finished) return;
    this.finished = true;
    const { state, suffix, pos, blockLen } = this;
    // FIPS 202 appends the SHA3/SHAKE domain-separation suffix before pad10*1.
    // These byte values already include the first padding bit, while the
    // final `0x80` below supplies the closing `1` bit in the last rate byte.
    state[pos] ^= suffix;
    // If that combined suffix lands in the last rate byte and already sets
    // bit 7, absorb it first so the final pad10*1 bit can be xored into a
    // fresh block.
    if ((suffix & 0x80) !== 0 && pos === blockLen - 1) this.keccak();
    state[blockLen - 1] ^= 0x80;
    this.keccak();
  }
  protected writeInto(out: TArg<Uint8Array>): TRet<Uint8Array> {
    aexists(this, false);
    abytes(out);
    this.finish();
    const bufferOut = this.state;
    const { blockLen } = this;
    for (let pos = 0, len = out.length; pos < len; ) {
      if (this.posOut >= blockLen) this.keccak();
      const take = Math.min(blockLen - this.posOut, len - pos);
      out.set(bufferOut.subarray(this.posOut, this.posOut + take), pos);
      this.posOut += take;
      pos += take;
    }
    return out as TRet<Uint8Array>;
  }
  xofInto(out: TArg<Uint8Array>): TRet<Uint8Array> {
    // Plain SHA3/Keccak usage with XOF is probably a mistake, but this base
    // class is also reused by SHAKE/cSHAKE/KMAC/TupleHash/ParallelHash/
    // TurboSHAKE/KangarooTwelve wrappers that intentionally enable XOF.
    if (!this.enableXOF) throw new Error('XOF is not enabled');
    return this.writeInto(out);
  }
  xof(bytes: number): TRet<Uint8Array> {
    anumber(bytes);
    return this.xofInto(new Uint8Array(bytes));
  }
  digestInto(out: TArg<Uint8Array>): void {
    aoutput(out, this);
    if (this.finished) throw new Error('digest() was already called');
    // `aoutput(...)` allows oversized buffers; digestInto() must fill only the advertised digest.
    this.writeInto(out.length === this.outputLen ? out : out.subarray(0, this.outputLen));
    this.destroy();
  }
  digest(): TRet<Uint8Array> {
    const out = new Uint8Array(this.outputLen);
    this.digestInto(out);
    return out as TRet<Uint8Array>;
  }
  destroy(): void {
    this.destroyed = true;
    clean(this.state);
  }
  _cloneInto(to?: Keccak): Keccak {
    const { blockLen, suffix, outputLen, rounds, enableXOF } = this;
    to ||= new Keccak(blockLen, suffix, outputLen, enableXOF, rounds);
    // Reused destinations can come from a different rate/capacity variant, so clone must rewrite
    // the sponge geometry as well as the state words.
    to.blockLen = blockLen;
    to.state32.set(this.state32);
    // Sponge padding and XOF output are positional, so both offsets are part of the clone state.
    to.pos = this.pos;
    to.posOut = this.posOut;
    to.finished = this.finished;
    to.rounds = rounds;
    // Suffix can change in cSHAKE
    to.suffix = suffix;
    to.outputLen = outputLen;
    to.enableXOF = enableXOF;
    // Clones must preserve the public capability bit too; `_KMAC` reuses this path and deep clone
    // tests compare instance fields directly, so leaving `canXOF` behind makes the clone lie.
    to.canXOF = this.canXOF;
    to.destroyed = this.destroyed;
    return to;
  }
}

function keccakOneShotCore(
  input: TArg<Uint8Array>,
  len: number,
  suffix: number,
  blockLen: number,
  outputLen: number,
  state: TArg<Uint8Array>,
  state32: TArg<Uint32Array>
): TRet<Uint8Array> {
  for (let i = 0; i < len; i++) state[i] = input[i];
  state[len] ^= suffix;
  state[blockLen - 1] ^= 0x80;
  swap32IfBE(state32);
  keccakP1600(state32, 24);
  swap32IfBE(state32);
  const out = new Uint8Array(outputLen);
  for (let i = 0; i < outputLen; i++) out[i] = state[i];
  return out as TRet<Uint8Array>;
}

const genKeccak = (
  suffix: number,
  blockLen: number,
  outputLen: number,
  info: TArg<HashInfo> = {}
) => {
  const stateful = createHasher(() => new Keccak(blockLen, suffix, outputLen), info);
  // Fixed-output calls that fit in one rate block skip stateful sponge setup. Keep all scratch
  // inside this factory so SHAKE-only and raw-permutation bundles do not retain the path.
  const sharedState = new Uint8Array(200);
  const sharedState32 = u32(sharedState);
  let busy = false;

  const hashOneShot = (input: TArg<Uint8Array>, len: number): TRet<Uint8Array> => {
    const state = busy ? new Uint8Array(200) : sharedState;
    const state32 = state === sharedState ? sharedState32 : u32(state);
    const shared = state === sharedState;
    if (shared) busy = true;
    try {
      return keccakOneShotCore(input, len, suffix, blockLen, outputLen, state, state32);
    } finally {
      for (let i = 0; i < 200; i++) state[i] = 0;
      if (shared) busy = false;
    }
  };
  return _wrapShortHash(stateful, blockLen - 1, hashOneShot);
};

/**
 * SHA3-224 hash function.
 * @param msg - message bytes to hash
 * @param opts - Reserved hash options.
 * @returns Digest bytes.
 * @example
 * Hash a message with SHA3-224.
 * ```ts
 * sha3_224(new Uint8Array([97, 98, 99]));
 * ```
 */
export const sha3_224: TRet<CHash> = /* @__PURE__ */ genKeccak(
  0x06,
  144,
  28,
  /* @__PURE__ */ oidNist(0x07)
);
/**
 * SHA3-256 hash function. Different from keccak-256.
 * @param msg - message bytes to hash
 * @param opts - Reserved hash options.
 * @returns Digest bytes.
 * @example
 * Hash a message with SHA3-256.
 * ```ts
 * sha3_256(new Uint8Array([97, 98, 99]));
 * ```
 */
export const sha3_256: TRet<CHash> = /* @__PURE__ */ genKeccak(
  0x06,
  136,
  32,
  /* @__PURE__ */ oidNist(0x08)
);
/**
 * SHA3-384 hash function.
 * @param msg - message bytes to hash
 * @param opts - Reserved hash options.
 * @returns Digest bytes.
 * @example
 * Hash a message with SHA3-384.
 * ```ts
 * sha3_384(new Uint8Array([97, 98, 99]));
 * ```
 */
export const sha3_384: TRet<CHash> = /* @__PURE__ */ genKeccak(
  0x06,
  104,
  48,
  /* @__PURE__ */ oidNist(0x09)
);
/**
 * SHA3-512 hash function.
 * @param msg - message bytes to hash
 * @param opts - Reserved hash options.
 * @returns Digest bytes.
 * @example
 * Hash a message with SHA3-512.
 * ```ts
 * sha3_512(new Uint8Array([97, 98, 99]));
 * ```
 */
export const sha3_512: TRet<CHash> = /* @__PURE__ */ genKeccak(
  0x06,
  72,
  64,
  /* @__PURE__ */ oidNist(0x0a)
);

/**
 * Keccak-224 hash function.
 * @param msg - message bytes to hash
 * @param opts - Reserved hash options.
 * @returns Digest bytes.
 * @example
 * Hash a message with Keccak-224.
 * ```ts
 * keccak_224(new Uint8Array([97, 98, 99]));
 * ```
 */
export const keccak_224: TRet<CHash> = /* @__PURE__ */ genKeccak(0x01, 144, 28);
/**
 * Keccak-256 hash function. Different from SHA3-256.
 * @param msg - message bytes to hash
 * @param opts - Reserved hash options.
 * @returns Digest bytes.
 * @example
 * Hash a message with Keccak-256.
 * ```ts
 * keccak_256(new Uint8Array([97, 98, 99]));
 * ```
 */
export const keccak_256: TRet<CHash> = /* @__PURE__ */ genKeccak(0x01, 136, 32);
/**
 * Keccak-384 hash function.
 * @param msg - message bytes to hash
 * @param opts - Reserved hash options.
 * @returns Digest bytes.
 * @example
 * Hash a message with Keccak-384.
 * ```ts
 * keccak_384(new Uint8Array([97, 98, 99]));
 * ```
 */
export const keccak_384: TRet<CHash> = /* @__PURE__ */ genKeccak(0x01, 104, 48);
/**
 * Keccak-512 hash function.
 * @param msg - message bytes to hash
 * @param opts - Reserved hash options.
 * @returns Digest bytes.
 * @example
 * Hash a message with Keccak-512.
 * ```ts
 * keccak_512(new Uint8Array([97, 98, 99]));
 * ```
 */
export const keccak_512: TRet<CHash> = /* @__PURE__ */ genKeccak(0x01, 72, 64);

/** Options for SHAKE XOF. */
export type ShakeOpts = {
  /** Desired number of output bytes. */
  dkLen?: number;
};

const genShake = (suffix: number, blockLen: number, outputLen: number, info: TArg<HashInfo> = {}) =>
  createHasher<Keccak, ShakeOpts>((opts: ShakeOpts = {}) => {
    opts = checkOpts({}, opts);
    return new Keccak(blockLen, suffix, opts.dkLen === undefined ? outputLen : opts.dkLen, true);
  }, info);

/**
 * SHAKE128 XOF with 128-bit security and a 16-byte default output.
 * @param msg - message bytes to hash
 * @param opts - Optional output-length override. See {@link ShakeOpts}.
 * @returns Digest bytes.
 * @example
 * Hash a message with SHAKE128.
 * ```ts
 * shake128(new Uint8Array([97, 98, 99]), { dkLen: 32 });
 * ```
 */
export const shake128: TRet<CHashXOF<Keccak, ShakeOpts>> =
  /* @__PURE__ */
  genShake(0x1f, 168, 16, /* @__PURE__ */ oidNist(0x0b));
/**
 * SHAKE256 XOF with 256-bit security and a 32-byte default output.
 * @param msg - message bytes to hash
 * @param opts - Optional output-length override. See {@link ShakeOpts}.
 * @returns Digest bytes.
 * @example
 * Hash a message with SHAKE256.
 * ```ts
 * shake256(new Uint8Array([97, 98, 99]), { dkLen: 64 });
 * ```
 */
export const shake256: TRet<CHashXOF<Keccak, ShakeOpts>> =
  /* @__PURE__ */
  genShake(0x1f, 136, 32, /* @__PURE__ */ oidNist(0x0c));

/**
 * SHAKE128 XOF with 256-bit output (NIST version).
 * @param msg - message bytes to hash
 * @param opts - Optional output-length override. See {@link ShakeOpts}.
 * @returns Digest bytes.
 * @example
 * Hash a message with SHAKE128 using a 32-byte default output.
 * ```ts
 * shake128_32(new Uint8Array([97, 98, 99]), { dkLen: 32 });
 * ```
 */
export const shake128_32: TRet<CHashXOF<Keccak, ShakeOpts>> =
  /* @__PURE__ */
  genShake(0x1f, 168, 32, /* @__PURE__ */ oidNist(0x0b));
/**
 * SHAKE256 XOF with 512-bit output (NIST version).
 * @param msg - message bytes to hash
 * @param opts - Optional output-length override. See {@link ShakeOpts}.
 * @returns Digest bytes.
 * @example
 * Hash a message with SHAKE256 using a 64-byte default output.
 * ```ts
 * shake256_64(new Uint8Array([97, 98, 99]), { dkLen: 64 });
 * ```
 */
export const shake256_64: TRet<CHashXOF<Keccak, ShakeOpts>> =
  /* @__PURE__ */
  genShake(0x1f, 136, 64, /* @__PURE__ */ oidNist(0x0c));
