name: Fuzz
on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  fuzz:
    uses: paulmillr/cryptofuzz/.github/workflows/noble-commit-fuzz.yml@a977f8bf03f1f9e68d512eb5b6ab09376a493a6f
    with:
      ref: ${{ github.sha }}
  slow:
    name: Slow large input tests
    uses: paulmillr/jsbt/.github/workflows/test-custom.yml@c138efca67d90dce86a7cc22c01d6b66d193ea7a
    with:
      npm-task: test:slow
  dos:
    name: DoS tests
    uses: paulmillr/jsbt/.github/workflows/test-custom.yml@c138efca67d90dce86a7cc22c01d6b66d193ea7a
    with:
      npm-task: test:dos
  acvp:
    name: ACVP tests
    uses: paulmillr/jsbt/.github/workflows/test-custom.yml@c138efca67d90dce86a7cc22c01d6b66d193ea7a
    with:
      npm-task: test:acvp
  kdf:
    name: KDF tests
    uses: paulmillr/jsbt/.github/workflows/test-custom.yml@c138efca67d90dce86a7cc22c01d6b66d193ea7a
    with:
      npm-task: test:kdf
