name: Run scheduled tests
on:
  schedule:
    - cron: '0 12 * * 1,4' # 06:00 bi-weekly (mon, thu)
  workflow_dispatch:
jobs:
  slow:
    name: Slow large input tests
    uses: paulmillr/jsbt/.github/workflows/test-custom.yml@7c25cb0b5eadac32bfedbb3b60ca0bd4289791f1
    with:
      npm-task: test:slow
  dos:
    name: DoS tests
    uses: paulmillr/jsbt/.github/workflows/test-custom.yml@7c25cb0b5eadac32bfedbb3b60ca0bd4289791f1
    with:
      npm-task: test:dos
  acvp:
    name: ACVP tests
    uses: paulmillr/jsbt/.github/workflows/test-custom.yml@7c25cb0b5eadac32bfedbb3b60ca0bd4289791f1
    with:
      npm-task: test:acvp
  kdf:
    name: KDF tests
    uses: paulmillr/jsbt/.github/workflows/test-custom.yml@7c25cb0b5eadac32bfedbb3b60ca0bd4289791f1
    with:
      npm-task: test:kdf
