name: Run scheduled tests
on:
  schedule:
    - cron: '0 12 * * 1,4' # 06:00 bi-weekly (mon, thu)
  workflow_dispatch:
jobs:
  slow:
    name: Slow large input tests
    uses: paulmillr/jsbt/.github/workflows/test-custom.yml@d156c5951d47d615d673d039aa03de6b9669449f
    with:
      npm-task: test:slow
  dos:
    name: DoS tests
    uses: paulmillr/jsbt/.github/workflows/test-custom.yml@d156c5951d47d615d673d039aa03de6b9669449f
    with:
      npm-task: test:dos
  acvp:
    name: ACVP tests
    uses: paulmillr/jsbt/.github/workflows/test-custom.yml@d156c5951d47d615d673d039aa03de6b9669449f
    with:
      npm-task: test:acvp
  kdf:
    name: KDF tests
    uses: paulmillr/jsbt/.github/workflows/test-custom.yml@d156c5951d47d615d673d039aa03de6b9669449f
    with:
      npm-task: test:kdf
